// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251020162018_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8e5c73-05d1-46c9-9b2d-e65aea98c80a"),
                            Date = new DateTime(2025, 10, 21, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(281),
                            Description = "A meetup for community members.",
                            IsPublic = true,
                            Location = "Community Center",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Community Meetup"
                        },
                        new
                        {
                            Id = new Guid("fc35537a-4342-4234-a4d4-76022157d207"),
                            Capacity = 50,
                            Date = new DateTime(2025, 10, 27, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(7975),
                            Description = "Annual technology conference.",
                            IsPublic = true,
                            Location = "Convention Hall",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Tech Conference"
                        },
                        new
                        {
                            Id = new Guid("ce470e6d-3d74-4fac-b542-b21f9eb44186"),
                            Date = new DateTime(2025, 11, 3, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8007),
                            Description = "A workshop for art enthusiasts.",
                            IsPublic = true,
                            Location = "Art Studio",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Art Workshop"
                        },
                        new
                        {
                            Id = new Guid("7d595805-51f8-45f3-9652-d1b9336689f6"),
                            Date = new DateTime(2025, 10, 23, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8012),
                            Description = "An exclusive dinner party for close friends.",
                            IsPublic = false,
                            Location = "Home",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Private Dinner Party"
                        },
                        new
                        {
                            Id = new Guid("630e1c97-0e60-4b78-a321-cd25ce86e7e3"),
                            Capacity = 8,
                            Date = new DateTime(2025, 10, 25, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8016),
                            Description = "Private board game session.",
                            IsPublic = false,
                            Location = "Game Cafe",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Board Game Night"
                        },
                        new
                        {
                            Id = new Guid("fc4b234d-2b08-4106-9af9-4830406e713b"),
                            Capacity = 20,
                            Date = new DateTime(2025, 10, 22, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Morning yoga session for all levels.",
                            IsPublic = true,
                            Location = "Wellness Center",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Yoga Class"
                        },
                        new
                        {
                            Id = new Guid("805fd53a-e4f4-47e3-8fe9-795bf5c50c3d"),
                            Capacity = 25,
                            Date = new DateTime(2025, 11, 19, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8024),
                            Description = "Annual family gathering.",
                            IsPublic = false,
                            Location = "Family Home",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Family Reunion"
                        },
                        new
                        {
                            Id = new Guid("d5610a25-697b-4e79-8751-9c501c07c89b"),
                            Date = new DateTime(2025, 12, 19, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8027),
                            Description = "Annual city-wide marathon event.",
                            IsPublic = true,
                            Location = "City Streets",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "City Marathon"
                        },
                        new
                        {
                            Id = new Guid("0397e27e-fb26-4b17-921e-d50489efcf99"),
                            Date = new DateTime(2025, 10, 30, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8030),
                            Description = "Monthly book club discussion.",
                            IsPublic = false,
                            Location = "Library Private Room",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Book Club Meeting"
                        },
                        new
                        {
                            Id = new Guid("b7c0bdf9-4f4e-48e4-9525-5d4e99fef16d"),
                            Capacity = 15,
                            Date = new DateTime(2025, 11, 1, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8054),
                            Description = "Learn to cook Italian cuisine.",
                            IsPublic = true,
                            Location = "Culinary Institute",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Cooking Workshop"
                        },
                        new
                        {
                            Id = new Guid("f77b8c32-37d5-4259-9f5c-00242d6ed13a"),
                            Capacity = 30,
                            Date = new DateTime(2025, 11, 9, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8061),
                            Description = "Private investment strategy seminar.",
                            IsPublic = false,
                            Location = "Financial Center",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Investment Seminar"
                        },
                        new
                        {
                            Id = new Guid("83d8a607-feba-465a-ac42-5d031446225a"),
                            Date = new DateTime(2025, 12, 4, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8064),
                            Description = "Open air music festival with multiple bands.",
                            IsPublic = true,
                            Location = "Park Amphitheater",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Music Festival"
                        },
                        new
                        {
                            Id = new Guid("8d1ae803-e6e8-417f-96b6-94a00fbbbd89"),
                            Date = new DateTime(2025, 10, 28, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8067),
                            Description = "Exclusive wine tasting for connoisseurs.",
                            IsPublic = false,
                            Location = "Private Wine Cellar",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Wine Tasting Evening"
                        },
                        new
                        {
                            Id = new Guid("492f8a7d-abd8-4dda-9237-eb9eccfc6be5"),
                            Capacity = 12,
                            Date = new DateTime(2025, 11, 4, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8070),
                            Description = "Professional photography workshop.",
                            IsPublic = true,
                            Location = "Photography Studio",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Photography Masterclass"
                        },
                        new
                        {
                            Id = new Guid("4d0043a3-b721-4d5e-ae48-330f64a37ea8"),
                            Capacity = 40,
                            Date = new DateTime(2025, 11, 7, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8073),
                            Description = "Private team building activities.",
                            IsPublic = false,
                            Location = "Adventure Park",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Corporate Team Building"
                        },
                        new
                        {
                            Id = new Guid("3aa1f8da-c834-4c99-9559-8d32db64e337"),
                            Date = new DateTime(2025, 11, 14, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8124),
                            Description = "Explore diverse street food from around the world.",
                            IsPublic = true,
                            Location = "Downtown Plaza",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Street Food Festival"
                        },
                        new
                        {
                            Id = new Guid("ba91c424-b9d0-48ac-aceb-72d6438d1a28"),
                            Date = new DateTime(2025, 10, 26, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8127),
                            Description = "Intimate poetry reading and discussion.",
                            IsPublic = false,
                            Location = "Cozy Bookshop",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Poetry Reading Circle"
                        },
                        new
                        {
                            Id = new Guid("e08e16b1-1a2d-4e4c-9b70-979d5cac1e6b"),
                            Capacity = 100,
                            Date = new DateTime(2025, 11, 24, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8130),
                            Description = "Learn about blockchain technology and cryptocurrency.",
                            IsPublic = true,
                            Location = "Tech Hub",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Blockchain Summit"
                        },
                        new
                        {
                            Id = new Guid("23c1e0ed-74ab-47ad-b2ed-9ecce8b99d97"),
                            Capacity = 15,
                            Date = new DateTime(2025, 10, 29, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8136),
                            Description = "Private celebration for the groom-to-be.",
                            IsPublic = false,
                            Location = "Resort",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Bachelor Party"
                        },
                        new
                        {
                            Id = new Guid("ca0bfc7d-d69e-457e-a615-7bf76a7fe302"),
                            Date = new DateTime(2025, 11, 29, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8138),
                            Description = "Community charity walk for local hospital.",
                            IsPublic = true,
                            Location = "City Park Trail",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Charity Walk"
                        },
                        new
                        {
                            Id = new Guid("accb2146-ab97-4947-8c4f-00b65fdff3ce"),
                            Date = new DateTime(2025, 11, 11, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8141),
                            Description = "Private launch event for new product line.",
                            IsPublic = false,
                            Location = "Luxury Hotel Ballroom",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Exclusive Product Launch"
                        },
                        new
                        {
                            Id = new Guid("3dd4a1ef-9eaf-46cd-93ab-efc323f7c114"),
                            Capacity = 25,
                            Date = new DateTime(2025, 10, 24, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8144),
                            Description = "Learn salsa dancing from scratch.",
                            IsPublic = true,
                            Location = "Dance Studio",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Dance Class Beginner"
                        },
                        new
                        {
                            Id = new Guid("417fed05-5862-48f7-ae02-179cc7c79c71"),
                            Capacity = 35,
                            Date = new DateTime(2025, 12, 9, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8147),
                            Description = "Celebrating 25 years together with close family.",
                            IsPublic = false,
                            Location = "Garden Venue",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Wedding Anniversary"
                        },
                        new
                        {
                            Id = new Guid("207403de-e129-4985-b6e2-b4dba076be82"),
                            Date = new DateTime(2025, 10, 23, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8151),
                            Description = "Showcase your talent at our weekly open mic.",
                            IsPublic = true,
                            Location = "Jazz Club",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Open Mic Night"
                        },
                        new
                        {
                            Id = new Guid("7058015f-33ca-4da7-8b5d-a8d63dfd21b5"),
                            Date = new DateTime(2025, 10, 31, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8154),
                            Description = "Quarterly business strategy meeting.",
                            IsPublic = false,
                            Location = "Conference Room A",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Strategy Planning Session"
                        },
                        new
                        {
                            Id = new Guid("202e3ac6-1d44-4154-803c-2a8b74742f7c"),
                            Capacity = 200,
                            Date = new DateTime(2025, 11, 17, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8158),
                            Description = "Annual science fair for students and enthusiasts.",
                            IsPublic = true,
                            Location = "Science Museum",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Science Fair"
                        },
                        new
                        {
                            Id = new Guid("dd90b841-5d30-4235-a29c-046e8da496b1"),
                            Capacity = 20,
                            Date = new DateTime(2025, 11, 2, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8162),
                            Description = "Secret birthday celebration.",
                            IsPublic = false,
                            Location = "Friend's House",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Birthday Surprise Party"
                        },
                        new
                        {
                            Id = new Guid("69355c02-06d9-4c07-af4c-5e44e9f82282"),
                            Date = new DateTime(2025, 11, 10, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8165),
                            Description = "Independent film screening and Q&A.",
                            IsPublic = true,
                            Location = "Indie Cinema",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Film Screening"
                        },
                        new
                        {
                            Id = new Guid("05534e12-a419-4a80-9299-8677f17879dc"),
                            Date = new DateTime(2025, 12, 14, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8168),
                            Description = "Private weekend meditation and mindfulness retreat.",
                            IsPublic = false,
                            Location = "Mountain Retreat Center",
                            OrganizerId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Title = "Meditation Retreat"
                        },
                        new
                        {
                            Id = new Guid("5fc8aa3e-4da7-4a26-a961-046cb3881f6d"),
                            Capacity = 500,
                            Date = new DateTime(2025, 11, 6, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8170),
                            Description = "Connect with top employers in the region.",
                            IsPublic = true,
                            Location = "Convention Center",
                            OrganizerId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Title = "Job Fair"
                        },
                        new
                        {
                            Id = new Guid("f0029ae0-3d6e-44f0-a000-59e9379d78c1"),
                            Capacity = 50,
                            Date = new DateTime(2025, 12, 29, 16, 20, 18, 226, DateTimeKind.Utc).AddTicks(8173),
                            Description = "Private reunion for class of 2010.",
                            IsPublic = false,
                            Location = "University Hall",
                            OrganizerId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Title = "Alumni Gathering"
                        });
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VisitorFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventId1");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitorEmail");

                    b.HasIndex("VisitorId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.HasIndex("EventId", "VisitorId")
                        .IsUnique();

                    b.ToTable("EventParticipants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5396665-2af9-4ddc-a587-8af37d98f27b"),
                            EventId = new Guid("0f8e5c73-05d1-46c9-9b2d-e65aea98c80a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(3956),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("555d7f4f-5e61-4709-804d-bad32d2653df"),
                            EventId = new Guid("0f8e5c73-05d1-46c9-9b2d-e65aea98c80a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4033),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("bc06a49b-4621-4829-a718-cc9356a192f6"),
                            EventId = new Guid("0f8e5c73-05d1-46c9-9b2d-e65aea98c80a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4035),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("f161de15-0590-4993-94e5-a07337149418"),
                            EventId = new Guid("0f8e5c73-05d1-46c9-9b2d-e65aea98c80a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4043),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("a2aba7bf-0c05-4fae-9aeb-f4a8f58b9968"),
                            EventId = new Guid("fc35537a-4342-4234-a4d4-76022157d207"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4044),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("71bf4aff-6bf0-4824-9878-21ce8d115c9f"),
                            EventId = new Guid("fc35537a-4342-4234-a4d4-76022157d207"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4057),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("d52b1c9d-eb81-4cd2-9ebf-2e1a3b349332"),
                            EventId = new Guid("fc35537a-4342-4234-a4d4-76022157d207"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4058),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("449a0345-be8a-4e38-9000-8dc235eae561"),
                            EventId = new Guid("fc35537a-4342-4234-a4d4-76022157d207"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4059),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("af8165b5-0316-465b-a8fc-ef83ff2fe8f7"),
                            EventId = new Guid("fc35537a-4342-4234-a4d4-76022157d207"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4060),
                            VisitorEmail = "james.anderson@example.com",
                            VisitorFirstName = "James",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            VisitorLastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("38b5756e-ef36-4469-9f29-c80b609c2f12"),
                            EventId = new Guid("ce470e6d-3d74-4fac-b542-b21f9eb44186"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4062),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("ab8656c9-d533-4626-b994-3dd6fcb87c39"),
                            EventId = new Guid("ce470e6d-3d74-4fac-b542-b21f9eb44186"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4063),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("72bcf2a2-0b55-49a6-bf32-6713495b2be9"),
                            EventId = new Guid("7d595805-51f8-45f3-9652-d1b9336689f6"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4066),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("a1ce9857-49dc-4999-80ce-11ab54937ff1"),
                            EventId = new Guid("7d595805-51f8-45f3-9652-d1b9336689f6"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4068),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("958f3ab1-83dd-4cb4-97ab-322bf8345452"),
                            EventId = new Guid("630e1c97-0e60-4b78-a321-cd25ce86e7e3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4069),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("3a9ede9e-d039-49f9-815b-39e78b2a2eea"),
                            EventId = new Guid("630e1c97-0e60-4b78-a321-cd25ce86e7e3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4071),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("d2e27f8a-a681-49c3-b2a0-babbc4096f17"),
                            EventId = new Guid("630e1c97-0e60-4b78-a321-cd25ce86e7e3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4072),
                            VisitorEmail = "liam.thomas@example.com",
                            VisitorFirstName = "Liam",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000006"),
                            VisitorLastName = "Thomas"
                        },
                        new
                        {
                            Id = new Guid("57dcaf9c-0e45-4f1d-8216-536aa65ca5ac"),
                            EventId = new Guid("630e1c97-0e60-4b78-a321-cd25ce86e7e3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4073),
                            VisitorEmail = "sophia.jackson@example.com",
                            VisitorFirstName = "Sophia",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000007"),
                            VisitorLastName = "Jackson"
                        },
                        new
                        {
                            Id = new Guid("32d3f4c5-cc1b-4735-9de2-33d15f21f57e"),
                            EventId = new Guid("630e1c97-0e60-4b78-a321-cd25ce86e7e3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4083),
                            VisitorEmail = "noah.white@example.com",
                            VisitorFirstName = "Noah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000008"),
                            VisitorLastName = "White"
                        },
                        new
                        {
                            Id = new Guid("a90fc315-648d-4e30-9cb1-b3bfba096436"),
                            EventId = new Guid("fc4b234d-2b08-4106-9af9-4830406e713b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4085),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("828fe674-103b-4463-9169-f9dd73aa51d9"),
                            EventId = new Guid("fc4b234d-2b08-4106-9af9-4830406e713b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4088),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("ca12990c-a2ba-4e6d-9d5d-42cdd9198e9f"),
                            EventId = new Guid("fc4b234d-2b08-4106-9af9-4830406e713b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4089),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("883b1a33-2b61-43e9-8409-391311cef80a"),
                            EventId = new Guid("fc4b234d-2b08-4106-9af9-4830406e713b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4090),
                            VisitorEmail = "william.martin@example.com",
                            VisitorFirstName = "William",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000009"),
                            VisitorLastName = "Martin"
                        },
                        new
                        {
                            Id = new Guid("4858bf43-1460-466c-984b-6ce5722406aa"),
                            EventId = new Guid("805fd53a-e4f4-47e3-8fe9-795bf5c50c3d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4092),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("b97e0c4d-0094-43ba-adf4-75061b8f5d77"),
                            EventId = new Guid("805fd53a-e4f4-47e3-8fe9-795bf5c50c3d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4094),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("db5ed79f-5a8e-449c-bc82-350984aa90cf"),
                            EventId = new Guid("805fd53a-e4f4-47e3-8fe9-795bf5c50c3d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4095),
                            VisitorEmail = "isabella.thompson@example.com",
                            VisitorFirstName = "Isabella",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000010"),
                            VisitorLastName = "Thompson"
                        },
                        new
                        {
                            Id = new Guid("2189d742-bf6e-4934-9477-c5a2e2fcb9aa"),
                            EventId = new Guid("d5610a25-697b-4e79-8751-9c501c07c89b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4097),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("e697a966-ed8a-4cb7-88dd-f84a795b1682"),
                            EventId = new Guid("d5610a25-697b-4e79-8751-9c501c07c89b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4098),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("f79b901d-fdbe-46a0-82aa-7aa3343ba56d"),
                            EventId = new Guid("d5610a25-697b-4e79-8751-9c501c07c89b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4101),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("d98fad0d-e7e3-4ff2-ab6d-9abf4b614052"),
                            EventId = new Guid("d5610a25-697b-4e79-8751-9c501c07c89b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4111),
                            VisitorEmail = "charlotte.lee@example.com",
                            VisitorFirstName = "Charlotte",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000011"),
                            VisitorLastName = "Lee"
                        },
                        new
                        {
                            Id = new Guid("61494a35-26ad-4add-a8c3-76a55e5dcf64"),
                            EventId = new Guid("d5610a25-697b-4e79-8751-9c501c07c89b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4112),
                            VisitorEmail = "ethan.walker@example.com",
                            VisitorFirstName = "Ethan",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000012"),
                            VisitorLastName = "Walker"
                        },
                        new
                        {
                            Id = new Guid("960ef1cb-8600-42ed-8518-5d29ca3896bf"),
                            EventId = new Guid("d5610a25-697b-4e79-8751-9c501c07c89b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4114),
                            VisitorEmail = "amelia.hall@example.com",
                            VisitorFirstName = "Amelia",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000013"),
                            VisitorLastName = "Hall"
                        },
                        new
                        {
                            Id = new Guid("055b9a80-39d1-4d47-9288-91db52ad40c8"),
                            EventId = new Guid("0397e27e-fb26-4b17-921e-d50489efcf99"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4116),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("0cbb463e-8641-416e-917a-dd246e0919fc"),
                            EventId = new Guid("0397e27e-fb26-4b17-921e-d50489efcf99"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4117),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("2740cb7f-67d6-496c-ae8b-40eb129983a3"),
                            EventId = new Guid("b7c0bdf9-4f4e-48e4-9525-5d4e99fef16d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4118),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("0394507a-980a-43b8-9dd7-6f5c87fffaa1"),
                            EventId = new Guid("b7c0bdf9-4f4e-48e4-9525-5d4e99fef16d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4120),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("30995362-cb04-4e90-b8f1-0551a3643fad"),
                            EventId = new Guid("b7c0bdf9-4f4e-48e4-9525-5d4e99fef16d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4123),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("12c78b0b-350f-4b43-bc6a-6a6f74367b28"),
                            EventId = new Guid("b7c0bdf9-4f4e-48e4-9525-5d4e99fef16d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4124),
                            VisitorEmail = "mia.young@example.com",
                            VisitorFirstName = "Mia",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000014"),
                            VisitorLastName = "Young"
                        },
                        new
                        {
                            Id = new Guid("dd993e6c-f763-4231-a061-66d1656fdc69"),
                            EventId = new Guid("f77b8c32-37d5-4259-9f5c-00242d6ed13a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4125),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("9dcc1724-de84-4405-9c83-72fc4d1aaad0"),
                            EventId = new Guid("f77b8c32-37d5-4259-9f5c-00242d6ed13a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4126),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("fa9af00d-f12c-4009-ac2c-7d7073f9b180"),
                            EventId = new Guid("f77b8c32-37d5-4259-9f5c-00242d6ed13a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4127),
                            VisitorEmail = "lucas.king@example.com",
                            VisitorFirstName = "Lucas",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000015"),
                            VisitorLastName = "King"
                        },
                        new
                        {
                            Id = new Guid("899f0ae4-d09d-4c8f-bb96-86051269a1e7"),
                            EventId = new Guid("83d8a607-feba-465a-ac42-5d031446225a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4138),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("1047f2f0-a83d-4b9d-9417-3c42882617ae"),
                            EventId = new Guid("83d8a607-feba-465a-ac42-5d031446225a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4139),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("5417a803-b2c1-4823-b08a-ba7a11b952a6"),
                            EventId = new Guid("83d8a607-feba-465a-ac42-5d031446225a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4141),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("a3884dd4-4262-4e15-a55c-ef10586df099"),
                            EventId = new Guid("83d8a607-feba-465a-ac42-5d031446225a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4144),
                            VisitorEmail = "james.anderson@example.com",
                            VisitorFirstName = "James",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            VisitorLastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("ba23dcba-9d9c-4143-ba7f-5b40995d51b7"),
                            EventId = new Guid("83d8a607-feba-465a-ac42-5d031446225a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4145),
                            VisitorEmail = "evelyn.hill@example.com",
                            VisitorFirstName = "Evelyn",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000016"),
                            VisitorLastName = "Hill"
                        },
                        new
                        {
                            Id = new Guid("7c7e145f-e5a1-4892-94bd-23a93310d38d"),
                            EventId = new Guid("8d1ae803-e6e8-417f-96b6-94a00fbbbd89"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4146),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("3ba4b10a-bf6a-4a6f-b123-8594b7150f1f"),
                            EventId = new Guid("8d1ae803-e6e8-417f-96b6-94a00fbbbd89"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4147),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("d91e9e51-8f9c-4e9e-9a44-3ddd7b39fc0d"),
                            EventId = new Guid("492f8a7d-abd8-4dda-9237-eb9eccfc6be5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4149),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("02319015-ce5b-4a96-b0da-697424210a62"),
                            EventId = new Guid("492f8a7d-abd8-4dda-9237-eb9eccfc6be5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4150),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("91c9854c-34eb-4094-afc7-84d1193816d5"),
                            EventId = new Guid("492f8a7d-abd8-4dda-9237-eb9eccfc6be5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4151),
                            VisitorEmail = "henry.scott@example.com",
                            VisitorFirstName = "Henry",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000017"),
                            VisitorLastName = "Scott"
                        },
                        new
                        {
                            Id = new Guid("c4423572-fd76-45b6-8f0f-ed45a9dcba16"),
                            EventId = new Guid("492f8a7d-abd8-4dda-9237-eb9eccfc6be5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4153),
                            VisitorEmail = "ella.green@example.com",
                            VisitorFirstName = "Ella",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000018"),
                            VisitorLastName = "Green"
                        },
                        new
                        {
                            Id = new Guid("cfa6598a-4c7e-4983-b43d-20119a953db0"),
                            EventId = new Guid("492f8a7d-abd8-4dda-9237-eb9eccfc6be5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4156),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("64625196-f130-48e9-9098-dcc0e2c0444e"),
                            EventId = new Guid("4d0043a3-b721-4d5e-ae48-330f64a37ea8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4166),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("c70b1b83-4187-4b79-a75e-656c5ac3143f"),
                            EventId = new Guid("4d0043a3-b721-4d5e-ae48-330f64a37ea8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4167),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("f5e6c64d-8722-4fee-9b74-2a5fad7c7f85"),
                            EventId = new Guid("3aa1f8da-c834-4c99-9559-8d32db64e337"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4169),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("59e4743e-26ee-453f-a6bb-02d442c35be2"),
                            EventId = new Guid("3aa1f8da-c834-4c99-9559-8d32db64e337"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4170),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("c1e982ec-a37f-4b69-85d2-8c3399ddc76c"),
                            EventId = new Guid("3aa1f8da-c834-4c99-9559-8d32db64e337"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4172),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("d0adfdd2-ab86-4007-8cb9-40843592258c"),
                            EventId = new Guid("3aa1f8da-c834-4c99-9559-8d32db64e337"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4173),
                            VisitorEmail = "daniel.nelson@example.com",
                            VisitorFirstName = "Daniel",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000019"),
                            VisitorLastName = "Nelson"
                        },
                        new
                        {
                            Id = new Guid("405b89ad-4209-4c35-aea0-998e76998ec4"),
                            EventId = new Guid("ba91c424-b9d0-48ac-aceb-72d6438d1a28"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4197),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("3ccfc262-27d7-48d1-9cc9-77ba2f8107a2"),
                            EventId = new Guid("ba91c424-b9d0-48ac-aceb-72d6438d1a28"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4200),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("41e4d341-dc8b-443b-93de-572686c0ded0"),
                            EventId = new Guid("e08e16b1-1a2d-4e4c-9b70-979d5cac1e6b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4203),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("881451d8-eac6-487d-8acf-ab8c1205547f"),
                            EventId = new Guid("e08e16b1-1a2d-4e4c-9b70-979d5cac1e6b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4204),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("6079475a-f4ef-4aa4-bda0-1d5509f18ae3"),
                            EventId = new Guid("e08e16b1-1a2d-4e4c-9b70-979d5cac1e6b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4206),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("4a3fddf5-ab7d-4804-8aea-1f8e0403d4d5"),
                            EventId = new Guid("e08e16b1-1a2d-4e4c-9b70-979d5cac1e6b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4207),
                            VisitorEmail = "james.anderson@example.com",
                            VisitorFirstName = "James",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            VisitorLastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("39bfab60-d6e9-469f-9f16-05f3b259991c"),
                            EventId = new Guid("e08e16b1-1a2d-4e4c-9b70-979d5cac1e6b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4217),
                            VisitorEmail = "samuel.perez@example.com",
                            VisitorFirstName = "Samuel",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000020"),
                            VisitorLastName = "Perez"
                        },
                        new
                        {
                            Id = new Guid("5051869b-1a99-4427-979e-aa5e110598b4"),
                            EventId = new Guid("e08e16b1-1a2d-4e4c-9b70-979d5cac1e6b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4218),
                            VisitorEmail = "lily.roberts@example.com",
                            VisitorFirstName = "Lily",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000021"),
                            VisitorLastName = "Roberts"
                        },
                        new
                        {
                            Id = new Guid("e2811cf7-acd9-452a-9b21-9f1278b582e9"),
                            EventId = new Guid("23c1e0ed-74ab-47ad-b2ed-9ecce8b99d97"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4219),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("2b0a9746-77c4-4628-bbd8-9a6ca2184421"),
                            EventId = new Guid("23c1e0ed-74ab-47ad-b2ed-9ecce8b99d97"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4222),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("83520fd6-d45e-4da6-a481-56e0a386acfe"),
                            EventId = new Guid("23c1e0ed-74ab-47ad-b2ed-9ecce8b99d97"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4223),
                            VisitorEmail = "matthew.turner@example.com",
                            VisitorFirstName = "Matthew",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000022"),
                            VisitorLastName = "Turner"
                        },
                        new
                        {
                            Id = new Guid("8432c00a-693c-4bea-8615-966055fe8749"),
                            EventId = new Guid("ca0bfc7d-d69e-457e-a615-7bf76a7fe302"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4225),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("68b1a4eb-dafc-43bc-9caa-b73839a8099b"),
                            EventId = new Guid("ca0bfc7d-d69e-457e-a615-7bf76a7fe302"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4226),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("4891b81b-e1a7-4c0f-b8d8-22816b5526e8"),
                            EventId = new Guid("ca0bfc7d-d69e-457e-a615-7bf76a7fe302"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4227),
                            VisitorEmail = "charlotte.lee@example.com",
                            VisitorFirstName = "Charlotte",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000011"),
                            VisitorLastName = "Lee"
                        },
                        new
                        {
                            Id = new Guid("6e09214b-cb58-4251-8e11-775d6a60c106"),
                            EventId = new Guid("ca0bfc7d-d69e-457e-a615-7bf76a7fe302"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4229),
                            VisitorEmail = "jackson.campbell@example.com",
                            VisitorFirstName = "Jackson",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000023"),
                            VisitorLastName = "Campbell"
                        },
                        new
                        {
                            Id = new Guid("befcac07-c759-499c-bc0e-e3b4f0c30198"),
                            EventId = new Guid("accb2146-ab97-4947-8c4f-00b65fdff3ce"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4230),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("054878d3-6e9b-4312-bfd0-6de5712a7a18"),
                            EventId = new Guid("accb2146-ab97-4947-8c4f-00b65fdff3ce"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4232),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("0aabc434-6679-47c4-a1c8-30ec2c95e455"),
                            EventId = new Guid("3dd4a1ef-9eaf-46cd-93ab-efc323f7c114"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4243),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("758ff923-edb4-4a80-af75-d84c0a3761e3"),
                            EventId = new Guid("3dd4a1ef-9eaf-46cd-93ab-efc323f7c114"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4245),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("c6f5f166-090f-4dc1-87b1-bae870909df7"),
                            EventId = new Guid("3dd4a1ef-9eaf-46cd-93ab-efc323f7c114"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4246),
                            VisitorEmail = "ella.green@example.com",
                            VisitorFirstName = "Ella",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000018"),
                            VisitorLastName = "Green"
                        },
                        new
                        {
                            Id = new Guid("84226374-533f-4028-909c-687f58c9753a"),
                            EventId = new Guid("3dd4a1ef-9eaf-46cd-93ab-efc323f7c114"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4248),
                            VisitorEmail = "ryan.evans@example.com",
                            VisitorFirstName = "Ryan",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000024"),
                            VisitorLastName = "Evans"
                        },
                        new
                        {
                            Id = new Guid("e7adac48-fdbd-4c7a-a9a0-2fc16b02756b"),
                            EventId = new Guid("417fed05-5862-48f7-ae02-179cc7c79c71"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4249),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("ada4cc12-0e47-4cdd-b529-14fae9f54c49"),
                            EventId = new Guid("417fed05-5862-48f7-ae02-179cc7c79c71"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4250),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("eae3bd96-f5a7-4333-8955-845e2fcc91ed"),
                            EventId = new Guid("207403de-e129-4985-b6e2-b4dba076be82"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4251),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("d28b5083-31e2-449d-b1ee-37a31413245e"),
                            EventId = new Guid("207403de-e129-4985-b6e2-b4dba076be82"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4253),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("d43f674a-ea92-4aba-bc09-a927d5c1bf8d"),
                            EventId = new Guid("207403de-e129-4985-b6e2-b4dba076be82"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4255),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("92077a22-4bae-4d01-8cb0-0154e89d5d82"),
                            EventId = new Guid("7058015f-33ca-4da7-8b5d-a8d63dfd21b5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4257),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("11871be9-92bc-44b6-9ad8-a73d56f7a270"),
                            EventId = new Guid("7058015f-33ca-4da7-8b5d-a8d63dfd21b5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4258),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("3cd42438-6c4c-4cc3-8996-1dd612d84a0e"),
                            EventId = new Guid("202e3ac6-1d44-4154-803c-2a8b74742f7c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4259),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("6df3109e-e47c-4f59-bcfc-49b399459d8d"),
                            EventId = new Guid("202e3ac6-1d44-4154-803c-2a8b74742f7c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4269),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("5270716f-930b-4cbe-8e4b-a8ae81a9439f"),
                            EventId = new Guid("202e3ac6-1d44-4154-803c-2a8b74742f7c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4270),
                            VisitorEmail = "hannah.collins@example.com",
                            VisitorFirstName = "Hannah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000025"),
                            VisitorLastName = "Collins"
                        },
                        new
                        {
                            Id = new Guid("44bc2eaf-64c3-4ee1-a831-d4928deb7b55"),
                            EventId = new Guid("202e3ac6-1d44-4154-803c-2a8b74742f7c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4271),
                            VisitorEmail = "isaac.stewart@example.com",
                            VisitorFirstName = "Isaac",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000026"),
                            VisitorLastName = "Stewart"
                        },
                        new
                        {
                            Id = new Guid("dfb56d9a-3fce-4c15-ac93-d0e6201c1b00"),
                            EventId = new Guid("202e3ac6-1d44-4154-803c-2a8b74742f7c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4273),
                            VisitorEmail = "ethan.walker@example.com",
                            VisitorFirstName = "Ethan",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000012"),
                            VisitorLastName = "Walker"
                        },
                        new
                        {
                            Id = new Guid("ab45bef3-dfaa-4a25-8b05-b404eae9f3b0"),
                            EventId = new Guid("dd90b841-5d30-4235-a29c-046e8da496b1"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4275),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("891d73a1-38ab-42e7-8d2f-f8926841c2a1"),
                            EventId = new Guid("dd90b841-5d30-4235-a29c-046e8da496b1"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4277),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("85671f3f-a9ff-4966-ae89-e91c76fdb8d7"),
                            EventId = new Guid("69355c02-06d9-4c07-af4c-5e44e9f82282"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4278),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("a9cc9a10-e606-4907-acdc-5c3f8e946566"),
                            EventId = new Guid("69355c02-06d9-4c07-af4c-5e44e9f82282"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4281),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("7dc117e1-9f66-41ad-b3b0-8a20295a9d9d"),
                            EventId = new Guid("69355c02-06d9-4c07-af4c-5e44e9f82282"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4282),
                            VisitorEmail = "evelyn.hill@example.com",
                            VisitorFirstName = "Evelyn",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000016"),
                            VisitorLastName = "Hill"
                        },
                        new
                        {
                            Id = new Guid("ae80eadb-7acb-4189-82ee-c4759c0cb3c6"),
                            EventId = new Guid("05534e12-a419-4a80-9299-8677f17879dc"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4284),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("5f8d1844-4fd9-41d2-8204-2f9f49130218"),
                            EventId = new Guid("05534e12-a419-4a80-9299-8677f17879dc"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4285),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("30c546b4-3aa4-413c-ad20-fa7995f58204"),
                            EventId = new Guid("5fc8aa3e-4da7-4a26-a961-046cb3881f6d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4286),
                            UserId = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0")
                        },
                        new
                        {
                            Id = new Guid("4a539104-647a-47b9-882d-6e23da3c89a1"),
                            EventId = new Guid("5fc8aa3e-4da7-4a26-a961-046cb3881f6d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4289),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("c40f29ba-2b16-4823-a941-a2cea3415da9"),
                            EventId = new Guid("5fc8aa3e-4da7-4a26-a961-046cb3881f6d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4290),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("156b0b66-a677-4711-b9ff-18b55a2f26e2"),
                            EventId = new Guid("5fc8aa3e-4da7-4a26-a961-046cb3881f6d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4291),
                            VisitorEmail = "caleb.reed@example.com",
                            VisitorFirstName = "Caleb",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000027"),
                            VisitorLastName = "Reed"
                        },
                        new
                        {
                            Id = new Guid("6e375e58-9a07-452a-bfd3-96be1cc8bb95"),
                            EventId = new Guid("5fc8aa3e-4da7-4a26-a961-046cb3881f6d"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4293),
                            VisitorEmail = "scarlett.cook@example.com",
                            VisitorFirstName = "Scarlett",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000028"),
                            VisitorLastName = "Cook"
                        },
                        new
                        {
                            Id = new Guid("55244de2-ca4d-4503-b913-f4c672e018a7"),
                            EventId = new Guid("f0029ae0-3d6e-44f0-a000-59e9379d78c1"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4294),
                            UserId = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd")
                        },
                        new
                        {
                            Id = new Guid("56412e32-cd2c-42be-a92e-cfbc3da7b035"),
                            EventId = new Guid("f0029ae0-3d6e-44f0-a000-59e9379d78c1"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4295),
                            UserId = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51")
                        },
                        new
                        {
                            Id = new Guid("367ebccd-51d2-4e4c-b3ea-91cc11b6b9b2"),
                            EventId = new Guid("f0029ae0-3d6e-44f0-a000-59e9379d78c1"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 20, 18, 230, DateTimeKind.Utc).AddTicks(4297),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        });
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c965145-0305-4c1f-8456-f73495e4bed0"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("156156c5-b131-425a-bed4-7cfaaa7434bd"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("e264cae1-afd4-441f-980b-fe47baf5bf51"),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        });
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.HasOne("Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.HasOne("Domain.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Event", null)
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId1");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Navigation("EventParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
