// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024092837_EventTags")]
    partial class EventTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a164386e-5195-4999-9469-4b2c206bb12b"),
                            Date = new DateTime(2025, 10, 25, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(932),
                            Description = "A meetup for community members.",
                            IsPublic = true,
                            Location = "Community Center",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Community Meetup"
                        },
                        new
                        {
                            Id = new Guid("066f6038-e920-4885-8186-67ae881c1f60"),
                            Capacity = 50,
                            Date = new DateTime(2025, 10, 31, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7598),
                            Description = "Annual technology conference.",
                            IsPublic = true,
                            Location = "Convention Hall",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Tech Conference"
                        },
                        new
                        {
                            Id = new Guid("5fa6e1e2-8da2-4934-ad96-99135d4cb5cf"),
                            Date = new DateTime(2025, 11, 7, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7619),
                            Description = "A workshop for art enthusiasts.",
                            IsPublic = true,
                            Location = "Art Studio",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Art Workshop"
                        },
                        new
                        {
                            Id = new Guid("1083361d-74af-422d-8f76-96b5de333422"),
                            Date = new DateTime(2025, 10, 27, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7623),
                            Description = "An exclusive dinner party for close friends.",
                            IsPublic = false,
                            Location = "Home",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Private Dinner Party"
                        },
                        new
                        {
                            Id = new Guid("95130403-cc55-4ad0-9ed1-551e384b43c8"),
                            Capacity = 8,
                            Date = new DateTime(2025, 10, 29, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7635),
                            Description = "Private board game session.",
                            IsPublic = false,
                            Location = "Game Cafe",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Board Game Night"
                        },
                        new
                        {
                            Id = new Guid("55f4780d-60c4-41f8-96bd-14a899b8ed6d"),
                            Capacity = 20,
                            Date = new DateTime(2025, 10, 26, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7660),
                            Description = "Morning yoga session for all levels.",
                            IsPublic = true,
                            Location = "Wellness Center",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Yoga Class"
                        },
                        new
                        {
                            Id = new Guid("65d7b78f-626e-4d21-83a7-53902ca0f671"),
                            Capacity = 25,
                            Date = new DateTime(2025, 11, 23, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7663),
                            Description = "Annual family gathering.",
                            IsPublic = false,
                            Location = "Family Home",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Family Reunion"
                        },
                        new
                        {
                            Id = new Guid("6199c1cc-a926-4aaf-acda-37a1e2dcf462"),
                            Date = new DateTime(2025, 12, 23, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7711),
                            Description = "Annual city-wide marathon event.",
                            IsPublic = true,
                            Location = "City Streets",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "City Marathon"
                        },
                        new
                        {
                            Id = new Guid("08135a0e-e395-47f1-b3e1-65e93b42c721"),
                            Date = new DateTime(2025, 11, 3, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7715),
                            Description = "Monthly book club discussion.",
                            IsPublic = false,
                            Location = "Library Private Room",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Book Club Meeting"
                        },
                        new
                        {
                            Id = new Guid("42a5302b-0b3c-4074-ab75-9c7f5933823b"),
                            Capacity = 15,
                            Date = new DateTime(2025, 11, 5, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7717),
                            Description = "Learn to cook Italian cuisine.",
                            IsPublic = true,
                            Location = "Culinary Institute",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Cooking Workshop"
                        },
                        new
                        {
                            Id = new Guid("15ef6d7d-07c1-458e-9a2b-507ceda36e39"),
                            Capacity = 30,
                            Date = new DateTime(2025, 11, 13, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7720),
                            Description = "Private investment strategy seminar.",
                            IsPublic = false,
                            Location = "Financial Center",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Investment Seminar"
                        },
                        new
                        {
                            Id = new Guid("3faa286f-7921-46c7-8752-64e535e1a5b0"),
                            Date = new DateTime(2025, 12, 8, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7724),
                            Description = "Open air music festival with multiple bands.",
                            IsPublic = true,
                            Location = "Park Amphitheater",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Music Festival"
                        },
                        new
                        {
                            Id = new Guid("8cee860b-00a0-4135-ab15-91791ceaf03f"),
                            Date = new DateTime(2025, 11, 1, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7728),
                            Description = "Exclusive wine tasting for connoisseurs.",
                            IsPublic = false,
                            Location = "Private Wine Cellar",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Wine Tasting Evening"
                        },
                        new
                        {
                            Id = new Guid("94975050-c7ed-47f2-94ed-6aff44b6b855"),
                            Capacity = 12,
                            Date = new DateTime(2025, 11, 8, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7731),
                            Description = "Professional photography workshop.",
                            IsPublic = true,
                            Location = "Photography Studio",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Photography Masterclass"
                        },
                        new
                        {
                            Id = new Guid("65b334c7-20be-4c4e-adbc-e8d15bba901c"),
                            Capacity = 40,
                            Date = new DateTime(2025, 11, 11, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7734),
                            Description = "Private team building activities.",
                            IsPublic = false,
                            Location = "Adventure Park",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Corporate Team Building"
                        },
                        new
                        {
                            Id = new Guid("ddf18263-d0c8-47e1-9305-929dffa78c60"),
                            Date = new DateTime(2025, 11, 18, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7737),
                            Description = "Explore diverse street food from around the world.",
                            IsPublic = true,
                            Location = "Downtown Plaza",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Street Food Festival"
                        },
                        new
                        {
                            Id = new Guid("4d1bd7bd-0155-4ce8-921b-c32f690c57d8"),
                            Date = new DateTime(2025, 10, 30, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7740),
                            Description = "Intimate poetry reading and discussion.",
                            IsPublic = false,
                            Location = "Cozy Bookshop",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Poetry Reading Circle"
                        },
                        new
                        {
                            Id = new Guid("50c6cff8-1c29-43f4-b39a-6c29285c9f3d"),
                            Capacity = 100,
                            Date = new DateTime(2025, 11, 28, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7742),
                            Description = "Learn about blockchain technology and cryptocurrency.",
                            IsPublic = true,
                            Location = "Tech Hub",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Blockchain Summit"
                        },
                        new
                        {
                            Id = new Guid("b848f0cb-5532-4522-93b4-39812aa4c9ba"),
                            Capacity = 15,
                            Date = new DateTime(2025, 11, 2, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7746),
                            Description = "Private celebration for the groom-to-be.",
                            IsPublic = false,
                            Location = "Resort",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Bachelor Party"
                        },
                        new
                        {
                            Id = new Guid("bc596c43-46a0-4070-8418-2786848a24ac"),
                            Date = new DateTime(2025, 12, 3, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7749),
                            Description = "Community charity walk for local hospital.",
                            IsPublic = true,
                            Location = "City Park Trail",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Charity Walk"
                        },
                        new
                        {
                            Id = new Guid("5a9b8b61-cce5-4b1f-ae04-5a4258bef4b6"),
                            Date = new DateTime(2025, 11, 15, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7754),
                            Description = "Private launch event for new product line.",
                            IsPublic = false,
                            Location = "Luxury Hotel Ballroom",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Exclusive Product Launch"
                        },
                        new
                        {
                            Id = new Guid("3c432d39-6e83-40cc-b7ad-9cccb3ab374c"),
                            Capacity = 25,
                            Date = new DateTime(2025, 10, 28, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7757),
                            Description = "Learn salsa dancing from scratch.",
                            IsPublic = true,
                            Location = "Dance Studio",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Dance Class Beginner"
                        },
                        new
                        {
                            Id = new Guid("3a9a17c3-7c99-4743-9c2e-f28f79195b12"),
                            Capacity = 35,
                            Date = new DateTime(2025, 12, 13, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7759),
                            Description = "Celebrating 25 years together with close family.",
                            IsPublic = false,
                            Location = "Garden Venue",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Wedding Anniversary"
                        },
                        new
                        {
                            Id = new Guid("38ed607a-e9a4-4103-ab96-2cf3c01900ca"),
                            Date = new DateTime(2025, 10, 27, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7762),
                            Description = "Showcase your talent at our weekly open mic.",
                            IsPublic = true,
                            Location = "Jazz Club",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Open Mic Night"
                        },
                        new
                        {
                            Id = new Guid("d1dfed48-5cf2-4be0-9999-f2aea14b6d68"),
                            Date = new DateTime(2025, 11, 4, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7765),
                            Description = "Quarterly business strategy meeting.",
                            IsPublic = false,
                            Location = "Conference Room A",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Strategy Planning Session"
                        },
                        new
                        {
                            Id = new Guid("c187e77c-1079-43b9-a57e-3f6a2dc155df"),
                            Capacity = 200,
                            Date = new DateTime(2025, 11, 21, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7768),
                            Description = "Annual science fair for students and enthusiasts.",
                            IsPublic = true,
                            Location = "Science Museum",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Science Fair"
                        },
                        new
                        {
                            Id = new Guid("2b69b5ad-d319-4276-aa1b-d31028f1feff"),
                            Capacity = 20,
                            Date = new DateTime(2025, 11, 6, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7770),
                            Description = "Secret birthday celebration.",
                            IsPublic = false,
                            Location = "Friend's House",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Birthday Surprise Party"
                        },
                        new
                        {
                            Id = new Guid("d6af4d6f-80e6-4892-9513-f6fe1c2e2b76"),
                            Date = new DateTime(2025, 11, 14, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7774),
                            Description = "Independent film screening and Q&A.",
                            IsPublic = true,
                            Location = "Indie Cinema",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Film Screening"
                        },
                        new
                        {
                            Id = new Guid("2c75cd8c-7d1f-430b-b7ef-c1877e79ee03"),
                            Date = new DateTime(2025, 12, 18, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7778),
                            Description = "Private weekend meditation and mindfulness retreat.",
                            IsPublic = false,
                            Location = "Mountain Retreat Center",
                            OrganizerId = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Title = "Meditation Retreat"
                        },
                        new
                        {
                            Id = new Guid("c3edb965-429a-4cdb-95ff-3bea931ab589"),
                            Capacity = 500,
                            Date = new DateTime(2025, 11, 10, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7805),
                            Description = "Connect with top employers in the region.",
                            IsPublic = true,
                            Location = "Convention Center",
                            OrganizerId = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Title = "Job Fair"
                        },
                        new
                        {
                            Id = new Guid("f9625c06-96a5-420c-b6ab-d267ef45c9a3"),
                            Capacity = 50,
                            Date = new DateTime(2026, 1, 2, 9, 28, 37, 107, DateTimeKind.Utc).AddTicks(7809),
                            Description = "Private reunion for class of 2010.",
                            IsPublic = false,
                            Location = "University Hall",
                            OrganizerId = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Title = "Alumni Gathering"
                        });
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VisitorFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitorEmail");

                    b.HasIndex("VisitorId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.HasIndex("EventId", "VisitorId")
                        .IsUnique();

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("Domain.Models.EventTag", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("a164386e-5195-4999-9469-4b2c206bb12b"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("8f2df889-c180-44e8-a727-6e5401b5ce90")
                        },
                        new
                        {
                            EventId = new Guid("a164386e-5195-4999-9469-4b2c206bb12b"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("b283fda1-c164-4f57-9525-78cfedc8ac39")
                        },
                        new
                        {
                            EventId = new Guid("a164386e-5195-4999-9469-4b2c206bb12b"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("f3f14426-50bf-4bc5-a78d-bfc06b43cdac")
                        },
                        new
                        {
                            EventId = new Guid("066f6038-e920-4885-8186-67ae881c1f60"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("398c3da3-0f74-4eae-a134-50d2188f8456")
                        },
                        new
                        {
                            EventId = new Guid("066f6038-e920-4885-8186-67ae881c1f60"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("041f6a2c-d4a4-4e45-8702-1dbf6f0ca902")
                        },
                        new
                        {
                            EventId = new Guid("066f6038-e920-4885-8186-67ae881c1f60"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("5b0b663e-835e-4105-91c7-4e5d60f371af")
                        },
                        new
                        {
                            EventId = new Guid("066f6038-e920-4885-8186-67ae881c1f60"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("96ad7a9a-d389-4e1b-aef1-02a4fa9bd4b0")
                        },
                        new
                        {
                            EventId = new Guid("5fa6e1e2-8da2-4934-ad96-99135d4cb5cf"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("026e7d94-7e29-478c-b10f-c22f841e6da2")
                        },
                        new
                        {
                            EventId = new Guid("5fa6e1e2-8da2-4934-ad96-99135d4cb5cf"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("c2238224-5ec3-4790-bf14-5c963c61831d")
                        },
                        new
                        {
                            EventId = new Guid("5fa6e1e2-8da2-4934-ad96-99135d4cb5cf"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("26b514f1-bcea-4c35-80c6-c70074d2ce5f")
                        },
                        new
                        {
                            EventId = new Guid("1083361d-74af-422d-8f76-96b5de333422"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("dd387f86-b970-4551-9dbf-91ad3f6c8388")
                        },
                        new
                        {
                            EventId = new Guid("1083361d-74af-422d-8f76-96b5de333422"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("bcc028b5-d08b-4f8c-a811-13fdc4341945")
                        },
                        new
                        {
                            EventId = new Guid("1083361d-74af-422d-8f76-96b5de333422"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("1585f821-8803-4c80-9223-e8d8723d0dbb")
                        },
                        new
                        {
                            EventId = new Guid("95130403-cc55-4ad0-9ed1-551e384b43c8"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("3372cf3b-5dc3-4123-8290-c75e6347e41a")
                        },
                        new
                        {
                            EventId = new Guid("95130403-cc55-4ad0-9ed1-551e384b43c8"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("1d74237c-59e5-4110-a4f2-b6c7bdb0f12a")
                        },
                        new
                        {
                            EventId = new Guid("55f4780d-60c4-41f8-96bd-14a899b8ed6d"),
                            TagId = new Guid("939a6e9f-5623-4263-9861-4ea02bbc238d"),
                            Id = new Guid("ce797dc4-1aeb-4e9d-89d3-1c981a315073")
                        },
                        new
                        {
                            EventId = new Guid("55f4780d-60c4-41f8-96bd-14a899b8ed6d"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("cb4e37e2-b087-4ec6-a0b2-fe6f2c0c70c6")
                        },
                        new
                        {
                            EventId = new Guid("55f4780d-60c4-41f8-96bd-14a899b8ed6d"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("4e3ea5ef-69ce-4c60-a77b-b63bb7faeb4d")
                        },
                        new
                        {
                            EventId = new Guid("65d7b78f-626e-4d21-83a7-53902ca0f671"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("1bb96de4-5470-41c0-a7d9-0ea824c8895a")
                        },
                        new
                        {
                            EventId = new Guid("65d7b78f-626e-4d21-83a7-53902ca0f671"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("7637872c-62aa-4770-bdec-5a74bce5e1e7")
                        },
                        new
                        {
                            EventId = new Guid("65d7b78f-626e-4d21-83a7-53902ca0f671"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("c96260f7-4a81-4de4-b59f-4c4a1145c161")
                        },
                        new
                        {
                            EventId = new Guid("6199c1cc-a926-4aaf-acda-37a1e2dcf462"),
                            TagId = new Guid("b289c6e5-ea00-4666-9e87-50720a94a2fe"),
                            Id = new Guid("7a87ca6f-fb4f-45eb-af89-bf8840f789af")
                        },
                        new
                        {
                            EventId = new Guid("6199c1cc-a926-4aaf-acda-37a1e2dcf462"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("dea341ab-a640-4a50-8a10-e2993cb9291e")
                        },
                        new
                        {
                            EventId = new Guid("6199c1cc-a926-4aaf-acda-37a1e2dcf462"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("f47dd1ed-2194-4e20-9e8b-ee69b7b72d96")
                        },
                        new
                        {
                            EventId = new Guid("6199c1cc-a926-4aaf-acda-37a1e2dcf462"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("66e9e4cc-608b-43d9-9f50-b1df2b4dab76")
                        },
                        new
                        {
                            EventId = new Guid("08135a0e-e395-47f1-b3e1-65e93b42c721"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("d1356d2d-1ba2-4821-aa59-5abfd96eb527")
                        },
                        new
                        {
                            EventId = new Guid("08135a0e-e395-47f1-b3e1-65e93b42c721"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("7cdec4c8-1f7c-47f9-a402-3f2fcb9e565e")
                        },
                        new
                        {
                            EventId = new Guid("08135a0e-e395-47f1-b3e1-65e93b42c721"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("50593eda-9f3d-437d-a521-d85790334cd8")
                        },
                        new
                        {
                            EventId = new Guid("42a5302b-0b3c-4074-ab75-9c7f5933823b"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("930675b8-5a5e-42e2-8713-b598950dbed6")
                        },
                        new
                        {
                            EventId = new Guid("42a5302b-0b3c-4074-ab75-9c7f5933823b"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("44ca58a7-e6df-40cc-82f1-d2edc4a5e394")
                        },
                        new
                        {
                            EventId = new Guid("42a5302b-0b3c-4074-ab75-9c7f5933823b"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("211c3faf-c750-4fc7-ad60-5ab9fdf1b57a")
                        },
                        new
                        {
                            EventId = new Guid("42a5302b-0b3c-4074-ab75-9c7f5933823b"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("ff6eb810-1015-432b-a157-4b8f2bbd37e3")
                        },
                        new
                        {
                            EventId = new Guid("15ef6d7d-07c1-458e-9a2b-507ceda36e39"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("a468f09d-3a49-4488-97ff-979e485c5417")
                        },
                        new
                        {
                            EventId = new Guid("15ef6d7d-07c1-458e-9a2b-507ceda36e39"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("04ac4bdf-e204-4062-b198-96069356d93e")
                        },
                        new
                        {
                            EventId = new Guid("15ef6d7d-07c1-458e-9a2b-507ceda36e39"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("7622ecc3-0e19-4f1d-83ac-3a0fde6b4311")
                        },
                        new
                        {
                            EventId = new Guid("15ef6d7d-07c1-458e-9a2b-507ceda36e39"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("0a9473b7-99ef-4101-8777-7f83d0c9da27")
                        },
                        new
                        {
                            EventId = new Guid("3faa286f-7921-46c7-8752-64e535e1a5b0"),
                            TagId = new Guid("939a6e9f-5623-4263-9861-4ea02bbc238d"),
                            Id = new Guid("18543483-e156-4d5f-9da0-04dd649fb08a")
                        },
                        new
                        {
                            EventId = new Guid("3faa286f-7921-46c7-8752-64e535e1a5b0"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("efe3b8f0-a152-443d-8fd0-c787378053b5")
                        },
                        new
                        {
                            EventId = new Guid("3faa286f-7921-46c7-8752-64e535e1a5b0"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("72ee4044-c060-4249-aa8b-05bae2bb8906")
                        },
                        new
                        {
                            EventId = new Guid("3faa286f-7921-46c7-8752-64e535e1a5b0"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("68fdc1ce-8382-4321-8930-21146a3e41ad")
                        },
                        new
                        {
                            EventId = new Guid("3faa286f-7921-46c7-8752-64e535e1a5b0"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("5ceca2a2-35bd-4835-a407-a3dbfa49070a")
                        },
                        new
                        {
                            EventId = new Guid("8cee860b-00a0-4135-ab15-91791ceaf03f"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("a8111b50-c723-44f6-9bf0-3e81abb9edc8")
                        },
                        new
                        {
                            EventId = new Guid("8cee860b-00a0-4135-ab15-91791ceaf03f"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("7f0a4701-b760-46c9-981c-236fdfd9b9c3")
                        },
                        new
                        {
                            EventId = new Guid("8cee860b-00a0-4135-ab15-91791ceaf03f"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("c404664d-a341-4a0c-9a77-ab9816ba8a11")
                        },
                        new
                        {
                            EventId = new Guid("94975050-c7ed-47f2-94ed-6aff44b6b855"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("aacc028b-9d47-4c69-9c31-0a8caf1d87cd")
                        },
                        new
                        {
                            EventId = new Guid("94975050-c7ed-47f2-94ed-6aff44b6b855"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("12c16f11-6b47-4874-b1d4-5de804d58e01")
                        },
                        new
                        {
                            EventId = new Guid("94975050-c7ed-47f2-94ed-6aff44b6b855"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("ca2f1cbb-65b0-4dfe-bd57-d030c0bef28e")
                        },
                        new
                        {
                            EventId = new Guid("94975050-c7ed-47f2-94ed-6aff44b6b855"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("5417f3e7-ab3c-42bb-b0fd-793a0f359867")
                        },
                        new
                        {
                            EventId = new Guid("65b334c7-20be-4c4e-adbc-e8d15bba901c"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("818ab4be-14e2-4117-83b8-a14e023dd0a3")
                        },
                        new
                        {
                            EventId = new Guid("65b334c7-20be-4c4e-adbc-e8d15bba901c"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("3a2a52b2-311e-40c0-a457-ec678d6b6ff9")
                        },
                        new
                        {
                            EventId = new Guid("65b334c7-20be-4c4e-adbc-e8d15bba901c"),
                            TagId = new Guid("b289c6e5-ea00-4666-9e87-50720a94a2fe"),
                            Id = new Guid("ee3a1c28-410a-48c4-bbdb-bc4b080586f0")
                        },
                        new
                        {
                            EventId = new Guid("65b334c7-20be-4c4e-adbc-e8d15bba901c"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("f67961b0-dfd8-4d9d-8c49-cc82841a1b20")
                        },
                        new
                        {
                            EventId = new Guid("ddf18263-d0c8-47e1-9305-929dffa78c60"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("cc02b13a-dcaa-4166-8de8-d75292b04ef3")
                        },
                        new
                        {
                            EventId = new Guid("ddf18263-d0c8-47e1-9305-929dffa78c60"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("97ab0944-3c21-4730-869c-4c30b04eb8c9")
                        },
                        new
                        {
                            EventId = new Guid("ddf18263-d0c8-47e1-9305-929dffa78c60"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("53a88253-fb0b-4c22-8506-971035961b98")
                        },
                        new
                        {
                            EventId = new Guid("ddf18263-d0c8-47e1-9305-929dffa78c60"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("99f5bc92-e5f7-4c38-90b6-0d02ccc5c4d8")
                        },
                        new
                        {
                            EventId = new Guid("4d1bd7bd-0155-4ce8-921b-c32f690c57d8"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("edc13a09-8779-4b97-a322-1f07abccb2d7")
                        },
                        new
                        {
                            EventId = new Guid("4d1bd7bd-0155-4ce8-921b-c32f690c57d8"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("9ca8d024-55fb-4e55-b561-230ba47839f6")
                        },
                        new
                        {
                            EventId = new Guid("4d1bd7bd-0155-4ce8-921b-c32f690c57d8"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("0fb02fad-e7a6-427d-959c-131bd6147638")
                        },
                        new
                        {
                            EventId = new Guid("50c6cff8-1c29-43f4-b39a-6c29285c9f3d"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("7e068c47-e284-43d6-a30d-44dc9ce1eee5")
                        },
                        new
                        {
                            EventId = new Guid("50c6cff8-1c29-43f4-b39a-6c29285c9f3d"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("a62268f9-ce40-4410-8fef-c4bca7554ca2")
                        },
                        new
                        {
                            EventId = new Guid("50c6cff8-1c29-43f4-b39a-6c29285c9f3d"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("648107a6-6e8e-4698-9690-035ec6027efc")
                        },
                        new
                        {
                            EventId = new Guid("50c6cff8-1c29-43f4-b39a-6c29285c9f3d"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("2277c9a2-2d6f-4e30-8807-393f25e3777e")
                        },
                        new
                        {
                            EventId = new Guid("50c6cff8-1c29-43f4-b39a-6c29285c9f3d"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("ff65fc9f-1689-4c1d-bcd8-b2f56ec2666c")
                        },
                        new
                        {
                            EventId = new Guid("b848f0cb-5532-4522-93b4-39812aa4c9ba"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("4e841c1c-9fd5-4f71-a3e6-3425fc76f3be")
                        },
                        new
                        {
                            EventId = new Guid("b848f0cb-5532-4522-93b4-39812aa4c9ba"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("0582c822-9176-41bf-b66e-e3df1aec0994")
                        },
                        new
                        {
                            EventId = new Guid("b848f0cb-5532-4522-93b4-39812aa4c9ba"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("4f70d996-147c-4c67-a2bf-db9af1eb444c")
                        },
                        new
                        {
                            EventId = new Guid("b848f0cb-5532-4522-93b4-39812aa4c9ba"),
                            TagId = new Guid("b289c6e5-ea00-4666-9e87-50720a94a2fe"),
                            Id = new Guid("dbe9c5d7-1757-4b31-bd09-5749470e6600")
                        },
                        new
                        {
                            EventId = new Guid("bc596c43-46a0-4070-8418-2786848a24ac"),
                            TagId = new Guid("b289c6e5-ea00-4666-9e87-50720a94a2fe"),
                            Id = new Guid("c5acdc1b-bc7e-49fa-82b7-fd11d93fa4ff")
                        },
                        new
                        {
                            EventId = new Guid("bc596c43-46a0-4070-8418-2786848a24ac"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("7e3c68ac-d0ab-4179-9922-19e5cd4c9c31")
                        },
                        new
                        {
                            EventId = new Guid("bc596c43-46a0-4070-8418-2786848a24ac"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("e1c668db-6f37-410c-bac4-78f354de5ec8")
                        },
                        new
                        {
                            EventId = new Guid("bc596c43-46a0-4070-8418-2786848a24ac"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("11ae5dd8-f58a-424b-a522-9b067a7ae9ea")
                        },
                        new
                        {
                            EventId = new Guid("5a9b8b61-cce5-4b1f-ae04-5a4258bef4b6"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("03025194-6eda-4471-b0bb-ea645a84ad00")
                        },
                        new
                        {
                            EventId = new Guid("5a9b8b61-cce5-4b1f-ae04-5a4258bef4b6"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("15c0a463-6254-4ec8-af4f-d0fe71f8eed2")
                        },
                        new
                        {
                            EventId = new Guid("5a9b8b61-cce5-4b1f-ae04-5a4258bef4b6"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("bee19f9f-8a18-4273-a3e5-a4755dbddb16")
                        },
                        new
                        {
                            EventId = new Guid("5a9b8b61-cce5-4b1f-ae04-5a4258bef4b6"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("da63a14c-3230-472c-8bc7-b09e7904cbbd")
                        },
                        new
                        {
                            EventId = new Guid("3c432d39-6e83-40cc-b7ad-9cccb3ab374c"),
                            TagId = new Guid("939a6e9f-5623-4263-9861-4ea02bbc238d"),
                            Id = new Guid("5b5fcc57-1d58-4df3-8476-ce7edea3b56e")
                        },
                        new
                        {
                            EventId = new Guid("3c432d39-6e83-40cc-b7ad-9cccb3ab374c"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("eabeda31-a329-48f6-887b-b2c4c6bb884b")
                        },
                        new
                        {
                            EventId = new Guid("3c432d39-6e83-40cc-b7ad-9cccb3ab374c"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("58e4289d-924e-4aa5-8c2d-9fba670a90d9")
                        },
                        new
                        {
                            EventId = new Guid("3c432d39-6e83-40cc-b7ad-9cccb3ab374c"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("bc880d3b-c0ee-42ea-bfd1-487dd91432da")
                        },
                        new
                        {
                            EventId = new Guid("3a9a17c3-7c99-4743-9c2e-f28f79195b12"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("4d398043-a7fb-46c9-902b-bddf8b65e0c7")
                        },
                        new
                        {
                            EventId = new Guid("3a9a17c3-7c99-4743-9c2e-f28f79195b12"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("06a4f4de-95f9-455e-b0ae-0ea172a6cf92")
                        },
                        new
                        {
                            EventId = new Guid("3a9a17c3-7c99-4743-9c2e-f28f79195b12"),
                            TagId = new Guid("939a6e9f-5623-4263-9861-4ea02bbc238d"),
                            Id = new Guid("260e2e97-8e62-4e8b-aa3a-fe3674b38fb0")
                        },
                        new
                        {
                            EventId = new Guid("38ed607a-e9a4-4103-ab96-2cf3c01900ca"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("53816e70-698f-41de-ae17-0ac6a7f2255f")
                        },
                        new
                        {
                            EventId = new Guid("38ed607a-e9a4-4103-ab96-2cf3c01900ca"),
                            TagId = new Guid("939a6e9f-5623-4263-9861-4ea02bbc238d"),
                            Id = new Guid("07030452-fa02-4ae1-8708-986f8c226792")
                        },
                        new
                        {
                            EventId = new Guid("38ed607a-e9a4-4103-ab96-2cf3c01900ca"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("ce4e0d11-fc4f-40d2-ab39-1dd79ae0b7b5")
                        },
                        new
                        {
                            EventId = new Guid("38ed607a-e9a4-4103-ab96-2cf3c01900ca"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("349664b0-6ec7-45d2-b2fb-c92b31c9557c")
                        },
                        new
                        {
                            EventId = new Guid("d1dfed48-5cf2-4be0-9999-f2aea14b6d68"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("3d0142b0-39e7-4e64-9069-5d1979433e3a")
                        },
                        new
                        {
                            EventId = new Guid("d1dfed48-5cf2-4be0-9999-f2aea14b6d68"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("675e8671-f3b0-4f21-904b-a9bc5a521dab")
                        },
                        new
                        {
                            EventId = new Guid("d1dfed48-5cf2-4be0-9999-f2aea14b6d68"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("4d53b16f-c580-4598-8d03-fb821688c303")
                        },
                        new
                        {
                            EventId = new Guid("c187e77c-1079-43b9-a57e-3f6a2dc155df"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("2552d54c-dbdb-4457-97ee-f002779b8f97")
                        },
                        new
                        {
                            EventId = new Guid("c187e77c-1079-43b9-a57e-3f6a2dc155df"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("c72b6f58-b712-4e6c-b82e-477b0f10979c")
                        },
                        new
                        {
                            EventId = new Guid("c187e77c-1079-43b9-a57e-3f6a2dc155df"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("f0f0b93c-7b55-4623-875c-d4ab925d6439")
                        },
                        new
                        {
                            EventId = new Guid("c187e77c-1079-43b9-a57e-3f6a2dc155df"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("12c36a82-3628-422e-9462-76c38c6fc13e")
                        },
                        new
                        {
                            EventId = new Guid("2b69b5ad-d319-4276-aa1b-d31028f1feff"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("131a1534-0eca-4d72-a5de-4803e1645fca")
                        },
                        new
                        {
                            EventId = new Guid("2b69b5ad-d319-4276-aa1b-d31028f1feff"),
                            TagId = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Id = new Guid("d1d91cbc-e071-43ce-83a3-2da3ac19f74a")
                        },
                        new
                        {
                            EventId = new Guid("2b69b5ad-d319-4276-aa1b-d31028f1feff"),
                            TagId = new Guid("939a6e9f-5623-4263-9861-4ea02bbc238d"),
                            Id = new Guid("a6c2459b-37f2-41ee-a007-0cf8ee9896b1")
                        },
                        new
                        {
                            EventId = new Guid("d6af4d6f-80e6-4892-9513-f6fe1c2e2b76"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("956aefe3-801c-4c7a-9329-26b9b7f1947c")
                        },
                        new
                        {
                            EventId = new Guid("d6af4d6f-80e6-4892-9513-f6fe1c2e2b76"),
                            TagId = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Id = new Guid("e41d07dc-ebf9-488a-b2f5-efdc79783d87")
                        },
                        new
                        {
                            EventId = new Guid("d6af4d6f-80e6-4892-9513-f6fe1c2e2b76"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("d003dcd9-dbb0-4984-b25f-3eb71543766f")
                        },
                        new
                        {
                            EventId = new Guid("d6af4d6f-80e6-4892-9513-f6fe1c2e2b76"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("20214e33-5568-4cf2-93ca-632dcfa9cf3c")
                        },
                        new
                        {
                            EventId = new Guid("2c75cd8c-7d1f-430b-b7ef-c1877e79ee03"),
                            TagId = new Guid("b289c6e5-ea00-4666-9e87-50720a94a2fe"),
                            Id = new Guid("6ae75659-2689-44df-808d-bb84f5c40163")
                        },
                        new
                        {
                            EventId = new Guid("2c75cd8c-7d1f-430b-b7ef-c1877e79ee03"),
                            TagId = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Id = new Guid("690b6582-6311-4fd4-8f90-cf72763057b4")
                        },
                        new
                        {
                            EventId = new Guid("2c75cd8c-7d1f-430b-b7ef-c1877e79ee03"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("caef7031-6928-4f5c-b443-930d13f4a3cc")
                        },
                        new
                        {
                            EventId = new Guid("2c75cd8c-7d1f-430b-b7ef-c1877e79ee03"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("b7babf30-5781-44b6-8240-4315747626f1")
                        },
                        new
                        {
                            EventId = new Guid("c3edb965-429a-4cdb-95ff-3bea931ab589"),
                            TagId = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Id = new Guid("0488c32b-e5ea-4e10-950e-690184d4e07f")
                        },
                        new
                        {
                            EventId = new Guid("c3edb965-429a-4cdb-95ff-3bea931ab589"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("464cdfd2-2ced-4968-ae97-2f15caa8f2b5")
                        },
                        new
                        {
                            EventId = new Guid("c3edb965-429a-4cdb-95ff-3bea931ab589"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("fe88f19a-c3e7-498b-b12d-fd6e88ee8a0d")
                        },
                        new
                        {
                            EventId = new Guid("c3edb965-429a-4cdb-95ff-3bea931ab589"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("e3f96e1e-22eb-4b7f-80f9-af87adc283b2")
                        },
                        new
                        {
                            EventId = new Guid("f9625c06-96a5-420c-b6ab-d267ef45c9a3"),
                            TagId = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Id = new Guid("0cfa3ac6-b82d-40b1-81af-dd1e7755cc29")
                        },
                        new
                        {
                            EventId = new Guid("f9625c06-96a5-420c-b6ab-d267ef45c9a3"),
                            TagId = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Id = new Guid("2c5effed-de2e-4ef7-924e-7fdcbb1bc628")
                        },
                        new
                        {
                            EventId = new Guid("f9625c06-96a5-420c-b6ab-d267ef45c9a3"),
                            TagId = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Id = new Guid("4475b1b8-2d87-40dc-943a-f40191356c62")
                        },
                        new
                        {
                            EventId = new Guid("f9625c06-96a5-420c-b6ab-d267ef45c9a3"),
                            TagId = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Id = new Guid("dacbd1df-832f-4812-898e-93eaaf5e7178")
                        });
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("148fd4b3-6fa8-4bec-94e2-0c3324228d31"),
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("c9359f9c-fb39-4887-8e20-c6af7e8aa5cb"),
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("20e96d1f-0434-4b80-b84b-56da7777d7c6"),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("86f5b247-a4d0-45ea-8a64-b46a91ef8bfe"),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("42468792-408c-40e6-b488-c0a87408fbb7"),
                            Name = "Networking"
                        },
                        new
                        {
                            Id = new Guid("939a6e9f-5623-4263-9861-4ea02bbc238d"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("b289c6e5-ea00-4666-9e87-50720a94a2fe"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("0d2425e8-6548-469e-a581-598a65336047"),
                            Name = "Food & Drink"
                        },
                        new
                        {
                            Id = new Guid("5f2e6e37-aff2-4c71-a666-0ea6e8d72db9"),
                            Name = "Business"
                        },
                        new
                        {
                            Id = new Guid("787fa4db-6546-40a3-90bb-343b2b5cc54d"),
                            Name = "Travel"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b1a61c0-3478-49f5-81c2-8700d3e16242"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("970427a2-f8e8-4b3f-8f80-6ef23b443635"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("1a60ee7e-01a5-49a0-ad6f-0a356101ff6f"),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        });
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.HasOne("Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.HasOne("Domain.Models.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.EventTag", b =>
                {
                    b.HasOne("Domain.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Navigation("EventParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
