// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c07bdf56-b67a-4309-83a7-500960f1f90d"),
                            Date = new DateTime(2025, 10, 28, 13, 58, 59, 469, DateTimeKind.Utc).AddTicks(8825),
                            Description = "A meetup for community members.",
                            IsPublic = true,
                            Location = "Community Center",
                            OrganizerId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8"),
                            Title = "Community Meetup"
                        },
                        new
                        {
                            Id = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            Capacity = 50,
                            Date = new DateTime(2025, 11, 3, 13, 58, 59, 470, DateTimeKind.Utc).AddTicks(6159),
                            Description = "Annual technology conference.",
                            IsPublic = true,
                            Location = "Convention Hall",
                            OrganizerId = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05"),
                            Title = "Tech Conference"
                        },
                        new
                        {
                            Id = new Guid("2221b619-1ed6-4fce-a3b1-305a73a0591b"),
                            Date = new DateTime(2025, 11, 10, 13, 58, 59, 470, DateTimeKind.Utc).AddTicks(6180),
                            Description = "A workshop for art enthusiasts.",
                            IsPublic = true,
                            Location = "Art Studio",
                            OrganizerId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12"),
                            Title = "Art Workshop"
                        },
                        new
                        {
                            Id = new Guid("1b025604-f256-49df-be11-bde5a2b02214"),
                            Date = new DateTime(2025, 10, 30, 13, 58, 59, 470, DateTimeKind.Utc).AddTicks(6186),
                            Description = "An exclusive dinner party for close friends.",
                            IsPublic = false,
                            Location = "Home",
                            OrganizerId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8"),
                            Title = "Private Dinner Party"
                        },
                        new
                        {
                            Id = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            Capacity = 8,
                            Date = new DateTime(2025, 11, 1, 13, 58, 59, 470, DateTimeKind.Utc).AddTicks(6197),
                            Description = "Private board game session.",
                            IsPublic = false,
                            Location = "Game Cafe",
                            OrganizerId = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05"),
                            Title = "Board Game Night"
                        },
                        new
                        {
                            Id = new Guid("c3d5fe13-4700-41e4-a9b1-043fdbc167aa"),
                            Capacity = 20,
                            Date = new DateTime(2025, 10, 29, 13, 58, 59, 470, DateTimeKind.Utc).AddTicks(6200),
                            Description = "Morning yoga session for all levels.",
                            IsPublic = true,
                            Location = "Wellness Center",
                            OrganizerId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12"),
                            Title = "Yoga Class"
                        },
                        new
                        {
                            Id = new Guid("66d5a5d1-364f-4d3a-87d8-639245a5981f"),
                            Capacity = 25,
                            Date = new DateTime(2025, 11, 26, 13, 58, 59, 470, DateTimeKind.Utc).AddTicks(6204),
                            Description = "Annual family gathering.",
                            IsPublic = false,
                            Location = "Family Home",
                            OrganizerId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8"),
                            Title = "Family Reunion"
                        },
                        new
                        {
                            Id = new Guid("274b4dce-fb1e-4262-8892-01286959c111"),
                            Date = new DateTime(2025, 12, 26, 13, 58, 59, 470, DateTimeKind.Utc).AddTicks(6207),
                            Description = "Annual city-wide marathon event.",
                            IsPublic = true,
                            Location = "City Streets",
                            OrganizerId = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05"),
                            Title = "City Marathon"
                        });
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VisitorFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitorEmail");

                    b.HasIndex("VisitorId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.HasIndex("EventId", "VisitorId")
                        .IsUnique();

                    b.ToTable("EventParticipants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("831332f2-04fb-41f0-ad7a-66ecbbaeae21"),
                            EventId = new Guid("c07bdf56-b67a-4309-83a7-500960f1f90d"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1590),
                            UserId = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05")
                        },
                        new
                        {
                            Id = new Guid("ae50ab5b-813c-43ac-be0d-939038a82315"),
                            EventId = new Guid("c07bdf56-b67a-4309-83a7-500960f1f90d"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1632),
                            UserId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12")
                        },
                        new
                        {
                            Id = new Guid("803404ee-7fca-4a9d-ae86-d07e01b34427"),
                            EventId = new Guid("c07bdf56-b67a-4309-83a7-500960f1f90d"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1635),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("da0f1f4a-cadb-44f5-8d73-da11e10d1f86"),
                            EventId = new Guid("c07bdf56-b67a-4309-83a7-500960f1f90d"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1636),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("77dc969a-bc7e-4c0f-8c69-b0900f6b3761"),
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1638),
                            UserId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8")
                        },
                        new
                        {
                            Id = new Guid("3212d30f-a20d-4ed3-a62e-1cf3b27dfecc"),
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1640),
                            UserId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12")
                        },
                        new
                        {
                            Id = new Guid("e21e54b0-ae34-43df-a94c-8ad7357dd4d0"),
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1641),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("fcabf99a-2ea5-486a-a6a3-c1d92fee5145"),
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1657),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("f3a8b7bb-aefd-4b58-a77d-070a02e8b425"),
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1658),
                            VisitorEmail = "james.anderson@example.com",
                            VisitorFirstName = "James",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            VisitorLastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("4846c4ae-7a00-424b-8795-f34d674c22a5"),
                            EventId = new Guid("2221b619-1ed6-4fce-a3b1-305a73a0591b"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1662),
                            UserId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8")
                        },
                        new
                        {
                            Id = new Guid("69840a48-5884-448b-918a-e753b8ef79ba"),
                            EventId = new Guid("2221b619-1ed6-4fce-a3b1-305a73a0591b"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1663),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("3bdc5eca-c19f-4105-8e16-bbf68641aa16"),
                            EventId = new Guid("1b025604-f256-49df-be11-bde5a2b02214"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1665),
                            UserId = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05")
                        },
                        new
                        {
                            Id = new Guid("6b6ddfde-b0df-4ccf-9eaa-dd04dc61c483"),
                            EventId = new Guid("1b025604-f256-49df-be11-bde5a2b02214"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1666),
                            UserId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12")
                        },
                        new
                        {
                            Id = new Guid("79726748-52ad-418f-8c1c-b04b95453b87"),
                            EventId = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1668),
                            UserId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8")
                        },
                        new
                        {
                            Id = new Guid("e27b1a69-1018-4733-ae3e-1459656fe532"),
                            EventId = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1669),
                            UserId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12")
                        },
                        new
                        {
                            Id = new Guid("872f3487-900b-4ff7-9367-bfc3013f953a"),
                            EventId = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1671),
                            VisitorEmail = "liam.thomas@example.com",
                            VisitorFirstName = "Liam",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000006"),
                            VisitorLastName = "Thomas"
                        },
                        new
                        {
                            Id = new Guid("3c9b6cbf-977b-4f5b-a225-7ed5bdfedff5"),
                            EventId = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1672),
                            VisitorEmail = "sophia.jackson@example.com",
                            VisitorFirstName = "Sophia",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000007"),
                            VisitorLastName = "Jackson"
                        },
                        new
                        {
                            Id = new Guid("fcfc0d36-0778-43d6-b9fd-a79eb20a64da"),
                            EventId = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1675),
                            VisitorEmail = "noah.white@example.com",
                            VisitorFirstName = "Noah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000008"),
                            VisitorLastName = "White"
                        },
                        new
                        {
                            Id = new Guid("7ccc97db-b8e7-46ae-98e8-8718f0b5f080"),
                            EventId = new Guid("c3d5fe13-4700-41e4-a9b1-043fdbc167aa"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1676),
                            UserId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8")
                        },
                        new
                        {
                            Id = new Guid("4dbf04c4-fa45-4796-aa7e-18de30abc038"),
                            EventId = new Guid("c3d5fe13-4700-41e4-a9b1-043fdbc167aa"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1677),
                            UserId = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05")
                        },
                        new
                        {
                            Id = new Guid("2c86d4bb-93bb-4697-abae-fb631310ded7"),
                            EventId = new Guid("c3d5fe13-4700-41e4-a9b1-043fdbc167aa"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1679),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("6f8d046e-dd93-43ee-b65f-292dccf7bd55"),
                            EventId = new Guid("c3d5fe13-4700-41e4-a9b1-043fdbc167aa"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1680),
                            VisitorEmail = "william.martin@example.com",
                            VisitorFirstName = "William",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000009"),
                            VisitorLastName = "Martin"
                        },
                        new
                        {
                            Id = new Guid("3bcd6972-b014-403a-8d52-c57c100efe3b"),
                            EventId = new Guid("66d5a5d1-364f-4d3a-87d8-639245a5981f"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1681),
                            UserId = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05")
                        },
                        new
                        {
                            Id = new Guid("8ab16daa-9f3b-4cb3-8f62-8ec8aeb4cdee"),
                            EventId = new Guid("66d5a5d1-364f-4d3a-87d8-639245a5981f"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1683),
                            UserId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12")
                        },
                        new
                        {
                            Id = new Guid("b52900f0-f42d-4c86-b2e4-6471965eb62b"),
                            EventId = new Guid("66d5a5d1-364f-4d3a-87d8-639245a5981f"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1684),
                            VisitorEmail = "isabella.thompson@example.com",
                            VisitorFirstName = "Isabella",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000010"),
                            VisitorLastName = "Thompson"
                        },
                        new
                        {
                            Id = new Guid("82ce941e-c851-435f-9848-c67d963a8a0a"),
                            EventId = new Guid("274b4dce-fb1e-4262-8892-01286959c111"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1687),
                            UserId = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8")
                        },
                        new
                        {
                            Id = new Guid("70539dca-5d30-4c2c-b7eb-029e963d909a"),
                            EventId = new Guid("274b4dce-fb1e-4262-8892-01286959c111"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1688),
                            UserId = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12")
                        },
                        new
                        {
                            Id = new Guid("7c4810bd-998c-4e2e-a1b2-7a949c2ed73f"),
                            EventId = new Guid("274b4dce-fb1e-4262-8892-01286959c111"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1689),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("ea2dff2f-7bd3-49d5-8c62-b9427c5d8381"),
                            EventId = new Guid("274b4dce-fb1e-4262-8892-01286959c111"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1690),
                            VisitorEmail = "charlotte.lee@example.com",
                            VisitorFirstName = "Charlotte",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000011"),
                            VisitorLastName = "Lee"
                        },
                        new
                        {
                            Id = new Guid("988a4dbb-4b77-41cb-be63-423d4cf540ce"),
                            EventId = new Guid("274b4dce-fb1e-4262-8892-01286959c111"),
                            JoinedAt = new DateTime(2025, 10, 27, 13, 58, 59, 472, DateTimeKind.Utc).AddTicks(1691),
                            VisitorEmail = "ethan.walker@example.com",
                            VisitorFirstName = "Ethan",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000012"),
                            VisitorLastName = "Walker"
                        });
                });

            modelBuilder.Entity("Domain.Models.EventTag", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EventTags");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("c07bdf56-b67a-4309-83a7-500960f1f90d"),
                            TagId = new Guid("e9621471-9f39-4ae2-8f5c-e0c5892ca6d1"),
                            Id = new Guid("cfe530c6-60d5-4cbb-b9fe-50927bc3c05a")
                        },
                        new
                        {
                            EventId = new Guid("c07bdf56-b67a-4309-83a7-500960f1f90d"),
                            TagId = new Guid("d16d2c39-ace7-4cd4-8f28-1d36e003ff4b"),
                            Id = new Guid("70fcba71-e0ad-48cd-b10c-f5077faaddd7")
                        },
                        new
                        {
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            TagId = new Guid("94c112bb-4e41-4db4-97b1-cfc6fe6587d0"),
                            Id = new Guid("cf044886-b6d5-4434-a33b-aa9f243d02ae")
                        },
                        new
                        {
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            TagId = new Guid("d16d2c39-ace7-4cd4-8f28-1d36e003ff4b"),
                            Id = new Guid("c98d4b5b-e27d-4d75-9484-90f931682db5")
                        },
                        new
                        {
                            EventId = new Guid("63cf53c6-1fa1-4db4-9ff4-6739984f5493"),
                            TagId = new Guid("e9621471-9f39-4ae2-8f5c-e0c5892ca6d1"),
                            Id = new Guid("baf63302-bf78-4210-892d-4e1a64daef41")
                        },
                        new
                        {
                            EventId = new Guid("2221b619-1ed6-4fce-a3b1-305a73a0591b"),
                            TagId = new Guid("30a8d388-ae2b-43ff-83a7-92491fb585e2"),
                            Id = new Guid("aba71761-0d3f-40a1-8dc2-f409ca7f1004")
                        },
                        new
                        {
                            EventId = new Guid("1b025604-f256-49df-be11-bde5a2b02214"),
                            TagId = new Guid("d16d2c39-ace7-4cd4-8f28-1d36e003ff4b"),
                            Id = new Guid("c2b8a3f3-bcd3-409e-9c23-7047ccd6e3ec")
                        },
                        new
                        {
                            EventId = new Guid("1b025604-f256-49df-be11-bde5a2b02214"),
                            TagId = new Guid("13164a74-f816-4a44-b5a3-1bd6c8699fae"),
                            Id = new Guid("d7a07e96-750e-4e2c-bbfb-1a9ea8b4b1df")
                        },
                        new
                        {
                            EventId = new Guid("1b025604-f256-49df-be11-bde5a2b02214"),
                            TagId = new Guid("e9621471-9f39-4ae2-8f5c-e0c5892ca6d1"),
                            Id = new Guid("1e1a0737-def4-4ccc-b7a9-0a236c7dda91")
                        },
                        new
                        {
                            EventId = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            TagId = new Guid("2802e8e5-94eb-4df8-b14f-e19bafed5bd0"),
                            Id = new Guid("a80bd549-40a0-48f6-be0a-ee0b567d34f9")
                        },
                        new
                        {
                            EventId = new Guid("b1bb35fc-a592-44b9-9a46-56ff721c7143"),
                            TagId = new Guid("e9621471-9f39-4ae2-8f5c-e0c5892ca6d1"),
                            Id = new Guid("a36a20dd-56d4-4995-8a31-269a527b1350")
                        },
                        new
                        {
                            EventId = new Guid("c3d5fe13-4700-41e4-a9b1-043fdbc167aa"),
                            TagId = new Guid("3e7159db-b3c9-4343-98a0-b8410ddd482b"),
                            Id = new Guid("c19d3aa4-c3a4-4a91-b8b9-a133efd75872")
                        },
                        new
                        {
                            EventId = new Guid("c3d5fe13-4700-41e4-a9b1-043fdbc167aa"),
                            TagId = new Guid("2802e8e5-94eb-4df8-b14f-e19bafed5bd0"),
                            Id = new Guid("cda6bea5-6a07-4111-bc23-fbf4fb9952ce")
                        },
                        new
                        {
                            EventId = new Guid("66d5a5d1-364f-4d3a-87d8-639245a5981f"),
                            TagId = new Guid("018cfac5-246b-4da6-8079-bb95b9e2f30d"),
                            Id = new Guid("71a16e6d-9420-4f19-85b5-6bce13a64cce")
                        },
                        new
                        {
                            EventId = new Guid("66d5a5d1-364f-4d3a-87d8-639245a5981f"),
                            TagId = new Guid("13164a74-f816-4a44-b5a3-1bd6c8699fae"),
                            Id = new Guid("c5a157ee-d004-4366-aadb-36f2d5c32e5d")
                        },
                        new
                        {
                            EventId = new Guid("66d5a5d1-364f-4d3a-87d8-639245a5981f"),
                            TagId = new Guid("e9621471-9f39-4ae2-8f5c-e0c5892ca6d1"),
                            Id = new Guid("5f6c95e1-1b43-4ffc-8baa-dbf61df892c8")
                        },
                        new
                        {
                            EventId = new Guid("274b4dce-fb1e-4262-8892-01286959c111"),
                            TagId = new Guid("eab92c44-85d9-4842-a537-3a43b1983cbd"),
                            Id = new Guid("61465c2a-abd5-4aa1-bb53-c4b448c3c5a6")
                        });
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94c112bb-4e41-4db4-97b1-cfc6fe6587d0"),
                            Name = "Technology",
                            NormalizedName = "technology"
                        },
                        new
                        {
                            Id = new Guid("30a8d388-ae2b-43ff-83a7-92491fb585e2"),
                            Name = "Art",
                            NormalizedName = "art"
                        },
                        new
                        {
                            Id = new Guid("3e7159db-b3c9-4343-98a0-b8410ddd482b"),
                            Name = "Health",
                            NormalizedName = "health"
                        },
                        new
                        {
                            Id = new Guid("2802e8e5-94eb-4df8-b14f-e19bafed5bd0"),
                            Name = "Education",
                            NormalizedName = "education"
                        },
                        new
                        {
                            Id = new Guid("e9621471-9f39-4ae2-8f5c-e0c5892ca6d1"),
                            Name = "Networking",
                            NormalizedName = "networking"
                        },
                        new
                        {
                            Id = new Guid("60696bb7-bc5c-4940-9d80-b9f9efbb8f35"),
                            Name = "Music",
                            NormalizedName = "music"
                        },
                        new
                        {
                            Id = new Guid("eab92c44-85d9-4842-a537-3a43b1983cbd"),
                            Name = "Sports",
                            NormalizedName = "sports"
                        },
                        new
                        {
                            Id = new Guid("13164a74-f816-4a44-b5a3-1bd6c8699fae"),
                            Name = "Food & Drink",
                            NormalizedName = "food&drink"
                        },
                        new
                        {
                            Id = new Guid("d16d2c39-ace7-4cd4-8f28-1d36e003ff4b"),
                            Name = "Business",
                            NormalizedName = "business"
                        },
                        new
                        {
                            Id = new Guid("018cfac5-246b-4da6-8079-bb95b9e2f30d"),
                            Name = "Travel",
                            NormalizedName = "travel"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e757b366-fe07-4985-970c-ba220f8f8ec8"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("025d9e06-04bb-4010-a637-e5a7d77e7d05"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("a7d4cd0a-774d-4790-a4b6-9919e26fbb12"),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        });
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.HasOne("Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.HasOne("Domain.Models.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.EventTag", b =>
                {
                    b.HasOne("Domain.Models.Event", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("EventTags");
                });
#pragma warning restore 612, 618
        }
    }
}
