// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2dd7112-93f2-4246-a34d-974bade50a76"),
                            Date = new DateTime(2025, 10, 21, 16, 37, 37, 373, DateTimeKind.Utc).AddTicks(4286),
                            Description = "A meetup for community members.",
                            IsPublic = true,
                            Location = "Community Center",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Community Meetup"
                        },
                        new
                        {
                            Id = new Guid("ab531bc9-33db-49e4-8e93-d89f1962e5a8"),
                            Capacity = 50,
                            Date = new DateTime(2025, 10, 27, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1282),
                            Description = "Annual technology conference.",
                            IsPublic = true,
                            Location = "Convention Hall",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Tech Conference"
                        },
                        new
                        {
                            Id = new Guid("de1c7bff-bff3-4761-9c1b-5c1f458d5cc0"),
                            Date = new DateTime(2025, 11, 3, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1340),
                            Description = "A workshop for art enthusiasts.",
                            IsPublic = true,
                            Location = "Art Studio",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Art Workshop"
                        },
                        new
                        {
                            Id = new Guid("d70f4151-99a8-4aaf-a4ba-251243e4673c"),
                            Date = new DateTime(2025, 10, 23, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1344),
                            Description = "An exclusive dinner party for close friends.",
                            IsPublic = false,
                            Location = "Home",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Private Dinner Party"
                        },
                        new
                        {
                            Id = new Guid("df0d4bee-0633-4653-bd37-488873be94b7"),
                            Capacity = 8,
                            Date = new DateTime(2025, 10, 25, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1348),
                            Description = "Private board game session.",
                            IsPublic = false,
                            Location = "Game Cafe",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Board Game Night"
                        },
                        new
                        {
                            Id = new Guid("e919e0e9-4b90-4188-bc98-9174f316908c"),
                            Capacity = 20,
                            Date = new DateTime(2025, 10, 22, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1352),
                            Description = "Morning yoga session for all levels.",
                            IsPublic = true,
                            Location = "Wellness Center",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Yoga Class"
                        },
                        new
                        {
                            Id = new Guid("5d00efb4-7e0f-4b5b-8895-32b2056de4c8"),
                            Capacity = 25,
                            Date = new DateTime(2025, 11, 19, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1363),
                            Description = "Annual family gathering.",
                            IsPublic = false,
                            Location = "Family Home",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Family Reunion"
                        },
                        new
                        {
                            Id = new Guid("e26d21a7-cb03-49fd-b551-35422fe177a4"),
                            Date = new DateTime(2025, 12, 19, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1366),
                            Description = "Annual city-wide marathon event.",
                            IsPublic = true,
                            Location = "City Streets",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "City Marathon"
                        },
                        new
                        {
                            Id = new Guid("3f78e6a7-9fa3-4934-b9d3-54f7b0bdaff0"),
                            Date = new DateTime(2025, 10, 30, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1380),
                            Description = "Monthly book club discussion.",
                            IsPublic = false,
                            Location = "Library Private Room",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Book Club Meeting"
                        },
                        new
                        {
                            Id = new Guid("c811e049-c654-478b-a6f6-b736a1237024"),
                            Capacity = 15,
                            Date = new DateTime(2025, 11, 1, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1383),
                            Description = "Learn to cook Italian cuisine.",
                            IsPublic = true,
                            Location = "Culinary Institute",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Cooking Workshop"
                        },
                        new
                        {
                            Id = new Guid("c6ac8b54-5627-44a7-9a3a-960f2573ec7a"),
                            Capacity = 30,
                            Date = new DateTime(2025, 11, 9, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1386),
                            Description = "Private investment strategy seminar.",
                            IsPublic = false,
                            Location = "Financial Center",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Investment Seminar"
                        },
                        new
                        {
                            Id = new Guid("11d38f7b-5d07-45d4-a39f-545e382c63f7"),
                            Date = new DateTime(2025, 12, 4, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1393),
                            Description = "Open air music festival with multiple bands.",
                            IsPublic = true,
                            Location = "Park Amphitheater",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Music Festival"
                        },
                        new
                        {
                            Id = new Guid("346809a6-4d97-48e3-ba23-6854ee999f94"),
                            Date = new DateTime(2025, 10, 28, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1397),
                            Description = "Exclusive wine tasting for connoisseurs.",
                            IsPublic = false,
                            Location = "Private Wine Cellar",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Wine Tasting Evening"
                        },
                        new
                        {
                            Id = new Guid("3667ca74-37f6-45b4-b7ce-fe902c2b1b2c"),
                            Capacity = 12,
                            Date = new DateTime(2025, 11, 4, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1399),
                            Description = "Professional photography workshop.",
                            IsPublic = true,
                            Location = "Photography Studio",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Photography Masterclass"
                        },
                        new
                        {
                            Id = new Guid("c9ae2a15-74c4-4c45-b9ee-4460881e7480"),
                            Capacity = 40,
                            Date = new DateTime(2025, 11, 7, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1404),
                            Description = "Private team building activities.",
                            IsPublic = false,
                            Location = "Adventure Park",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Corporate Team Building"
                        },
                        new
                        {
                            Id = new Guid("0b3441a6-b2b0-4e22-ac78-a93286c3ee08"),
                            Date = new DateTime(2025, 11, 14, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1407),
                            Description = "Explore diverse street food from around the world.",
                            IsPublic = true,
                            Location = "Downtown Plaza",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Street Food Festival"
                        },
                        new
                        {
                            Id = new Guid("838a0093-0d94-43b6-8036-3c6f48eb3818"),
                            Date = new DateTime(2025, 10, 26, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1409),
                            Description = "Intimate poetry reading and discussion.",
                            IsPublic = false,
                            Location = "Cozy Bookshop",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Poetry Reading Circle"
                        },
                        new
                        {
                            Id = new Guid("ceda62e1-9ab2-4920-9465-cb049e79dfc3"),
                            Capacity = 100,
                            Date = new DateTime(2025, 11, 24, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1412),
                            Description = "Learn about blockchain technology and cryptocurrency.",
                            IsPublic = true,
                            Location = "Tech Hub",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Blockchain Summit"
                        },
                        new
                        {
                            Id = new Guid("0792ae44-85dc-4e58-97ef-39ebf3f34444"),
                            Capacity = 15,
                            Date = new DateTime(2025, 10, 29, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1415),
                            Description = "Private celebration for the groom-to-be.",
                            IsPublic = false,
                            Location = "Resort",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Bachelor Party"
                        },
                        new
                        {
                            Id = new Guid("b0f8fd5f-9535-44eb-9814-31c8b060a928"),
                            Date = new DateTime(2025, 11, 29, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1417),
                            Description = "Community charity walk for local hospital.",
                            IsPublic = true,
                            Location = "City Park Trail",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Charity Walk"
                        },
                        new
                        {
                            Id = new Guid("a8e253b6-ec75-4f46-ac7d-b365afcd5e22"),
                            Date = new DateTime(2025, 11, 11, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1420),
                            Description = "Private launch event for new product line.",
                            IsPublic = false,
                            Location = "Luxury Hotel Ballroom",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Exclusive Product Launch"
                        },
                        new
                        {
                            Id = new Guid("556144b0-e80d-4608-9849-d0aaac573ecb"),
                            Capacity = 25,
                            Date = new DateTime(2025, 10, 24, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1423),
                            Description = "Learn salsa dancing from scratch.",
                            IsPublic = true,
                            Location = "Dance Studio",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Dance Class Beginner"
                        },
                        new
                        {
                            Id = new Guid("c58dda12-1562-4a73-bd57-02ff9f1b3e57"),
                            Capacity = 35,
                            Date = new DateTime(2025, 12, 9, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1427),
                            Description = "Celebrating 25 years together with close family.",
                            IsPublic = false,
                            Location = "Garden Venue",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Wedding Anniversary"
                        },
                        new
                        {
                            Id = new Guid("09189be9-c6ff-4f4c-9c6c-db8517d9530b"),
                            Date = new DateTime(2025, 10, 23, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1430),
                            Description = "Showcase your talent at our weekly open mic.",
                            IsPublic = true,
                            Location = "Jazz Club",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Open Mic Night"
                        },
                        new
                        {
                            Id = new Guid("0e5b218c-bca8-4989-8454-ed869ff1f951"),
                            Date = new DateTime(2025, 10, 31, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1433),
                            Description = "Quarterly business strategy meeting.",
                            IsPublic = false,
                            Location = "Conference Room A",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Strategy Planning Session"
                        },
                        new
                        {
                            Id = new Guid("0b5063d3-cf21-4c5a-9c40-4f7418ff5948"),
                            Capacity = 200,
                            Date = new DateTime(2025, 11, 17, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1455),
                            Description = "Annual science fair for students and enthusiasts.",
                            IsPublic = true,
                            Location = "Science Museum",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Science Fair"
                        },
                        new
                        {
                            Id = new Guid("012740e4-3721-49ea-b91d-6b3bc0b8dc95"),
                            Capacity = 20,
                            Date = new DateTime(2025, 11, 2, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1458),
                            Description = "Secret birthday celebration.",
                            IsPublic = false,
                            Location = "Friend's House",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Birthday Surprise Party"
                        },
                        new
                        {
                            Id = new Guid("e5081037-258b-4944-854a-36542c9eb709"),
                            Date = new DateTime(2025, 11, 10, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1461),
                            Description = "Independent film screening and Q&A.",
                            IsPublic = true,
                            Location = "Indie Cinema",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Film Screening"
                        },
                        new
                        {
                            Id = new Guid("45d0162b-5f24-4881-a2c5-0426608656b5"),
                            Date = new DateTime(2025, 12, 14, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1464),
                            Description = "Private weekend meditation and mindfulness retreat.",
                            IsPublic = false,
                            Location = "Mountain Retreat Center",
                            OrganizerId = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Title = "Meditation Retreat"
                        },
                        new
                        {
                            Id = new Guid("e7c06fc3-4ba4-4179-a38c-2dc285710dd5"),
                            Capacity = 500,
                            Date = new DateTime(2025, 11, 6, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1466),
                            Description = "Connect with top employers in the region.",
                            IsPublic = true,
                            Location = "Convention Center",
                            OrganizerId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Title = "Job Fair"
                        },
                        new
                        {
                            Id = new Guid("9d1fcacd-47ce-4bbf-b692-785e84451c5e"),
                            Capacity = 50,
                            Date = new DateTime(2025, 12, 29, 16, 37, 37, 374, DateTimeKind.Utc).AddTicks(1471),
                            Description = "Private reunion for class of 2010.",
                            IsPublic = false,
                            Location = "University Hall",
                            OrganizerId = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Title = "Alumni Gathering"
                        });
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VisitorFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitorEmail");

                    b.HasIndex("VisitorId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.HasIndex("EventId", "VisitorId")
                        .IsUnique();

                    b.ToTable("EventParticipants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ab90b8f-c8dd-4ec5-9386-4c6d58b1c5e6"),
                            EventId = new Guid("b2dd7112-93f2-4246-a34d-974bade50a76"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6120),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("ae51bc20-ebd0-4842-8bb3-3ed3bc3e077e"),
                            EventId = new Guid("b2dd7112-93f2-4246-a34d-974bade50a76"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6156),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("d44dbdb2-3e48-43ee-9778-25146c077a70"),
                            EventId = new Guid("b2dd7112-93f2-4246-a34d-974bade50a76"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6160),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("579980e4-f12f-44d6-9bc5-0264aa5533b9"),
                            EventId = new Guid("b2dd7112-93f2-4246-a34d-974bade50a76"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6162),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("13952bae-54f0-47a3-8420-4bc2b842fb4c"),
                            EventId = new Guid("ab531bc9-33db-49e4-8e93-d89f1962e5a8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6175),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("c8f7362c-c3cd-437d-915c-966249e6c2c5"),
                            EventId = new Guid("ab531bc9-33db-49e4-8e93-d89f1962e5a8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6176),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("c914fa0a-6857-4ba8-93c2-fe695357c273"),
                            EventId = new Guid("ab531bc9-33db-49e4-8e93-d89f1962e5a8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6178),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("dca5c675-37bb-41e1-9877-5941a36b050f"),
                            EventId = new Guid("ab531bc9-33db-49e4-8e93-d89f1962e5a8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6185),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("2cf0beec-2af7-4c21-8ef0-8e13c6f53a08"),
                            EventId = new Guid("ab531bc9-33db-49e4-8e93-d89f1962e5a8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6187),
                            VisitorEmail = "james.anderson@example.com",
                            VisitorFirstName = "James",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            VisitorLastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("673fb09a-2dd8-42c8-8868-040bc0352d0c"),
                            EventId = new Guid("de1c7bff-bff3-4761-9c1b-5c1f458d5cc0"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6192),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("68f4d5d5-7285-4046-8b25-ac8246f35008"),
                            EventId = new Guid("de1c7bff-bff3-4761-9c1b-5c1f458d5cc0"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6193),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("d07a98ed-c1fe-4bcd-abb2-566eae061997"),
                            EventId = new Guid("d70f4151-99a8-4aaf-a4ba-251243e4673c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6195),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("05f78387-815d-4151-a6f8-10ac4a2bfe79"),
                            EventId = new Guid("d70f4151-99a8-4aaf-a4ba-251243e4673c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6196),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("62bf6b53-0074-417f-8cef-c438d41a9313"),
                            EventId = new Guid("df0d4bee-0633-4653-bd37-488873be94b7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6197),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("d8b6266a-eaf4-4c7b-91a1-c9eb00ce1e53"),
                            EventId = new Guid("df0d4bee-0633-4653-bd37-488873be94b7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6198),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("522c3879-2abe-4b29-8dfb-d7711e487536"),
                            EventId = new Guid("df0d4bee-0633-4653-bd37-488873be94b7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6201),
                            VisitorEmail = "liam.thomas@example.com",
                            VisitorFirstName = "Liam",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000006"),
                            VisitorLastName = "Thomas"
                        },
                        new
                        {
                            Id = new Guid("c26c8aa0-6183-4dc3-bf9a-8fe28233d704"),
                            EventId = new Guid("df0d4bee-0633-4653-bd37-488873be94b7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6211),
                            VisitorEmail = "sophia.jackson@example.com",
                            VisitorFirstName = "Sophia",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000007"),
                            VisitorLastName = "Jackson"
                        },
                        new
                        {
                            Id = new Guid("7bec266d-9eb2-4848-89d2-e28b95f551c8"),
                            EventId = new Guid("df0d4bee-0633-4653-bd37-488873be94b7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6212),
                            VisitorEmail = "noah.white@example.com",
                            VisitorFirstName = "Noah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000008"),
                            VisitorLastName = "White"
                        },
                        new
                        {
                            Id = new Guid("9a996f11-789e-41ba-820a-bec9c08c86a1"),
                            EventId = new Guid("e919e0e9-4b90-4188-bc98-9174f316908c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6214),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("825f1e2b-e4fd-427f-9fd6-581ca075b49f"),
                            EventId = new Guid("e919e0e9-4b90-4188-bc98-9174f316908c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6215),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("63554936-ec27-4fb6-9f63-351b52328730"),
                            EventId = new Guid("e919e0e9-4b90-4188-bc98-9174f316908c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6216),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("704c39e1-131d-4205-896f-1c4dbc4e4d50"),
                            EventId = new Guid("e919e0e9-4b90-4188-bc98-9174f316908c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6218),
                            VisitorEmail = "william.martin@example.com",
                            VisitorFirstName = "William",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000009"),
                            VisitorLastName = "Martin"
                        },
                        new
                        {
                            Id = new Guid("ca931f3b-54f4-4b68-8d0b-229d5f3f5231"),
                            EventId = new Guid("5d00efb4-7e0f-4b5b-8895-32b2056de4c8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6219),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("1ae54910-f164-4355-9c47-2d6e17904e0b"),
                            EventId = new Guid("5d00efb4-7e0f-4b5b-8895-32b2056de4c8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6222),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("2b74166d-0639-4875-aada-6d74e3e1a245"),
                            EventId = new Guid("5d00efb4-7e0f-4b5b-8895-32b2056de4c8"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6360),
                            VisitorEmail = "isabella.thompson@example.com",
                            VisitorFirstName = "Isabella",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000010"),
                            VisitorLastName = "Thompson"
                        },
                        new
                        {
                            Id = new Guid("c096526b-a7af-43b5-a934-f6fc7b0fb1f8"),
                            EventId = new Guid("e26d21a7-cb03-49fd-b551-35422fe177a4"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6361),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("fa57dddd-c17f-45e0-92cc-3157a0aa5e50"),
                            EventId = new Guid("e26d21a7-cb03-49fd-b551-35422fe177a4"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6363),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("b057508c-d7f6-40c4-953c-578d04cb57b4"),
                            EventId = new Guid("e26d21a7-cb03-49fd-b551-35422fe177a4"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6364),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("7b519f50-bb8f-4889-a256-077471f17d99"),
                            EventId = new Guid("e26d21a7-cb03-49fd-b551-35422fe177a4"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6376),
                            VisitorEmail = "charlotte.lee@example.com",
                            VisitorFirstName = "Charlotte",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000011"),
                            VisitorLastName = "Lee"
                        },
                        new
                        {
                            Id = new Guid("e202b5f6-b3a6-403b-9a6d-1117337744b1"),
                            EventId = new Guid("e26d21a7-cb03-49fd-b551-35422fe177a4"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6377),
                            VisitorEmail = "ethan.walker@example.com",
                            VisitorFirstName = "Ethan",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000012"),
                            VisitorLastName = "Walker"
                        },
                        new
                        {
                            Id = new Guid("4334f768-d253-44c6-9daf-8cfc3fa9896f"),
                            EventId = new Guid("e26d21a7-cb03-49fd-b551-35422fe177a4"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6378),
                            VisitorEmail = "amelia.hall@example.com",
                            VisitorFirstName = "Amelia",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000013"),
                            VisitorLastName = "Hall"
                        },
                        new
                        {
                            Id = new Guid("471f1301-d706-4998-9d80-e4a16e058bc6"),
                            EventId = new Guid("3f78e6a7-9fa3-4934-b9d3-54f7b0bdaff0"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6381),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("8028b52e-6fd6-4d2b-a7c0-fdbff818bfe3"),
                            EventId = new Guid("3f78e6a7-9fa3-4934-b9d3-54f7b0bdaff0"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6382),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("aa71eec5-5b7d-46b2-b959-4f8c0ce22c56"),
                            EventId = new Guid("c811e049-c654-478b-a6f6-b736a1237024"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6384),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("bea70451-8ee0-4fbc-ae94-aad6a1cb8ae7"),
                            EventId = new Guid("c811e049-c654-478b-a6f6-b736a1237024"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6385),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("1be4cf63-3387-4d6b-8b12-dd5cd469e95d"),
                            EventId = new Guid("c811e049-c654-478b-a6f6-b736a1237024"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6386),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("5cd5e2e7-18c4-40b7-b272-d7a519b4ea3b"),
                            EventId = new Guid("c811e049-c654-478b-a6f6-b736a1237024"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6387),
                            VisitorEmail = "mia.young@example.com",
                            VisitorFirstName = "Mia",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000014"),
                            VisitorLastName = "Young"
                        },
                        new
                        {
                            Id = new Guid("1e708072-d408-435a-8b94-a7fa71bca25a"),
                            EventId = new Guid("c6ac8b54-5627-44a7-9a3a-960f2573ec7a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6389),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("642e9536-22b8-4b5b-ab4a-319e6e1052d7"),
                            EventId = new Guid("c6ac8b54-5627-44a7-9a3a-960f2573ec7a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6391),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("d3c5720e-9833-4289-ae26-8ceba05df6a7"),
                            EventId = new Guid("c6ac8b54-5627-44a7-9a3a-960f2573ec7a"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6394),
                            VisitorEmail = "lucas.king@example.com",
                            VisitorFirstName = "Lucas",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000015"),
                            VisitorLastName = "King"
                        },
                        new
                        {
                            Id = new Guid("c3a5b44e-f454-412c-a969-becb06073adc"),
                            EventId = new Guid("11d38f7b-5d07-45d4-a39f-545e382c63f7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6404),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("c899d159-eed2-4904-8a9f-b9f52a1e4c33"),
                            EventId = new Guid("11d38f7b-5d07-45d4-a39f-545e382c63f7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6405),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("69167eca-85b7-4ed1-b5f0-2335448c464a"),
                            EventId = new Guid("11d38f7b-5d07-45d4-a39f-545e382c63f7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6406),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("11e65a86-39ef-4046-89de-862961ac4e21"),
                            EventId = new Guid("11d38f7b-5d07-45d4-a39f-545e382c63f7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6408),
                            VisitorEmail = "james.anderson@example.com",
                            VisitorFirstName = "James",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            VisitorLastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("17a27259-515f-49e8-8651-f04b00e941e0"),
                            EventId = new Guid("11d38f7b-5d07-45d4-a39f-545e382c63f7"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6409),
                            VisitorEmail = "evelyn.hill@example.com",
                            VisitorFirstName = "Evelyn",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000016"),
                            VisitorLastName = "Hill"
                        },
                        new
                        {
                            Id = new Guid("b8070290-f815-4b77-9a99-e729c70b4403"),
                            EventId = new Guid("346809a6-4d97-48e3-ba23-6854ee999f94"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6410),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("6cae62e3-04e8-4876-95dd-effef6b84bca"),
                            EventId = new Guid("346809a6-4d97-48e3-ba23-6854ee999f94"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6411),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("81ecc259-fa61-40c3-b426-1e56a5dac401"),
                            EventId = new Guid("3667ca74-37f6-45b4-b7ce-fe902c2b1b2c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6414),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("512e98a2-9fe8-4d76-8fd9-c41f956e5a93"),
                            EventId = new Guid("3667ca74-37f6-45b4-b7ce-fe902c2b1b2c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6416),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("030adbfc-1005-4d17-bf65-ccd0c9b85242"),
                            EventId = new Guid("3667ca74-37f6-45b4-b7ce-fe902c2b1b2c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6419),
                            VisitorEmail = "henry.scott@example.com",
                            VisitorFirstName = "Henry",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000017"),
                            VisitorLastName = "Scott"
                        },
                        new
                        {
                            Id = new Guid("4a404139-5640-4a6a-a80f-0c53909a275a"),
                            EventId = new Guid("3667ca74-37f6-45b4-b7ce-fe902c2b1b2c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6420),
                            VisitorEmail = "ella.green@example.com",
                            VisitorFirstName = "Ella",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000018"),
                            VisitorLastName = "Green"
                        },
                        new
                        {
                            Id = new Guid("f4614ba4-264a-4b53-aceb-7c64faa7cce9"),
                            EventId = new Guid("3667ca74-37f6-45b4-b7ce-fe902c2b1b2c"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6431),
                            VisitorEmail = "emma.garcia@example.com",
                            VisitorFirstName = "Emma",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            VisitorLastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("3246a508-3848-408a-8a73-2480d797958b"),
                            EventId = new Guid("c9ae2a15-74c4-4c45-b9ee-4460881e7480"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6433),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("718964f9-8f07-40a2-b5ee-4fa7a9b4127a"),
                            EventId = new Guid("c9ae2a15-74c4-4c45-b9ee-4460881e7480"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6435),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("230c4027-a046-41c9-9931-d17323606181"),
                            EventId = new Guid("0b3441a6-b2b0-4e22-ac78-a93286c3ee08"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6436),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("fc336f60-5380-4c54-bddd-702666e9b151"),
                            EventId = new Guid("0b3441a6-b2b0-4e22-ac78-a93286c3ee08"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6439),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("5832ce42-3788-45f7-b191-fc2dd86124fc"),
                            EventId = new Guid("0b3441a6-b2b0-4e22-ac78-a93286c3ee08"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6440),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("fccf7a7f-0776-4040-a336-e831dfaaf5d4"),
                            EventId = new Guid("0b3441a6-b2b0-4e22-ac78-a93286c3ee08"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6441),
                            VisitorEmail = "daniel.nelson@example.com",
                            VisitorFirstName = "Daniel",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000019"),
                            VisitorLastName = "Nelson"
                        },
                        new
                        {
                            Id = new Guid("5b101f47-7f18-4783-9c42-b2b886db9a16"),
                            EventId = new Guid("838a0093-0d94-43b6-8036-3c6f48eb3818"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6443),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("27e5d7cf-cd8e-42ff-913a-9ed5807dc3f6"),
                            EventId = new Guid("838a0093-0d94-43b6-8036-3c6f48eb3818"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6444),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("9e1f72c9-88e3-4a7a-838f-de0efd091054"),
                            EventId = new Guid("ceda62e1-9ab2-4920-9465-cb049e79dfc3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6445),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("3047cb8d-9aea-46ff-9f8f-5581e658e4cc"),
                            EventId = new Guid("ceda62e1-9ab2-4920-9465-cb049e79dfc3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6446),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("8424013f-0e07-4176-918f-82b987e01ea7"),
                            EventId = new Guid("ceda62e1-9ab2-4920-9465-cb049e79dfc3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6447),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("f5edd7de-bb4a-4e97-9e9f-b45d0f9b547a"),
                            EventId = new Guid("ceda62e1-9ab2-4920-9465-cb049e79dfc3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6459),
                            VisitorEmail = "james.anderson@example.com",
                            VisitorFirstName = "James",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            VisitorLastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("d4e46fad-587f-41cc-82ba-89cfbc402623"),
                            EventId = new Guid("ceda62e1-9ab2-4920-9465-cb049e79dfc3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6461),
                            VisitorEmail = "samuel.perez@example.com",
                            VisitorFirstName = "Samuel",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000020"),
                            VisitorLastName = "Perez"
                        },
                        new
                        {
                            Id = new Guid("13673fc6-e196-4874-b571-c738437f20b9"),
                            EventId = new Guid("ceda62e1-9ab2-4920-9465-cb049e79dfc3"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6462),
                            VisitorEmail = "lily.roberts@example.com",
                            VisitorFirstName = "Lily",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000021"),
                            VisitorLastName = "Roberts"
                        },
                        new
                        {
                            Id = new Guid("05d15b3e-bf49-48a8-b599-bcbf492c6abd"),
                            EventId = new Guid("0792ae44-85dc-4e58-97ef-39ebf3f34444"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6463),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("9e97df8d-ccee-4098-8d0c-9ef486aea7a1"),
                            EventId = new Guid("0792ae44-85dc-4e58-97ef-39ebf3f34444"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6464),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("52871682-2916-463f-98ab-ea76d3eab2c3"),
                            EventId = new Guid("0792ae44-85dc-4e58-97ef-39ebf3f34444"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6466),
                            VisitorEmail = "matthew.turner@example.com",
                            VisitorFirstName = "Matthew",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000022"),
                            VisitorLastName = "Turner"
                        },
                        new
                        {
                            Id = new Guid("74876f61-b204-410a-acf6-cee76bbc7ffa"),
                            EventId = new Guid("b0f8fd5f-9535-44eb-9814-31c8b060a928"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6467),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("d8fce23c-83dc-474e-8995-480bcd91fd85"),
                            EventId = new Guid("b0f8fd5f-9535-44eb-9814-31c8b060a928"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6468),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("232c3d29-2ccc-42c2-bb06-c23e344deefe"),
                            EventId = new Guid("b0f8fd5f-9535-44eb-9814-31c8b060a928"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6471),
                            VisitorEmail = "charlotte.lee@example.com",
                            VisitorFirstName = "Charlotte",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000011"),
                            VisitorLastName = "Lee"
                        },
                        new
                        {
                            Id = new Guid("ddd9fae1-2a88-4459-bd6b-0c6a553f0259"),
                            EventId = new Guid("b0f8fd5f-9535-44eb-9814-31c8b060a928"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6473),
                            VisitorEmail = "jackson.campbell@example.com",
                            VisitorFirstName = "Jackson",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000023"),
                            VisitorLastName = "Campbell"
                        },
                        new
                        {
                            Id = new Guid("b1c034b5-b011-4960-a5b7-077c4740acda"),
                            EventId = new Guid("a8e253b6-ec75-4f46-ac7d-b365afcd5e22"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6474),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("31926d34-4547-4f6f-99a2-aa421f1d3a27"),
                            EventId = new Guid("a8e253b6-ec75-4f46-ac7d-b365afcd5e22"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6475),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("9800fc2b-5003-45fd-ac6a-f4c974f5b530"),
                            EventId = new Guid("556144b0-e80d-4608-9849-d0aaac573ecb"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6485),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("d4e92965-61f9-484f-942b-3a4b33cb5b6c"),
                            EventId = new Guid("556144b0-e80d-4608-9849-d0aaac573ecb"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6486),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("f9a5b9c8-ffa7-43e5-b1a9-6741b26448e8"),
                            EventId = new Guid("556144b0-e80d-4608-9849-d0aaac573ecb"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6488),
                            VisitorEmail = "ella.green@example.com",
                            VisitorFirstName = "Ella",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000018"),
                            VisitorLastName = "Green"
                        },
                        new
                        {
                            Id = new Guid("352e9b51-c685-4762-9c5b-f605d5cf2e1a"),
                            EventId = new Guid("556144b0-e80d-4608-9849-d0aaac573ecb"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6489),
                            VisitorEmail = "ryan.evans@example.com",
                            VisitorFirstName = "Ryan",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000024"),
                            VisitorLastName = "Evans"
                        },
                        new
                        {
                            Id = new Guid("1667da5a-64d3-449b-bcb4-e1a78d169413"),
                            EventId = new Guid("c58dda12-1562-4a73-bd57-02ff9f1b3e57"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6496),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("db5cfef8-7ce4-4879-9b77-1a2a1a3574bf"),
                            EventId = new Guid("c58dda12-1562-4a73-bd57-02ff9f1b3e57"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6497),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("22f6b3e6-be68-411b-a731-303d02736ea7"),
                            EventId = new Guid("09189be9-c6ff-4f4c-9c6c-db8517d9530b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6531),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("83c66ad2-d8d4-4e45-86d6-d79848df7e25"),
                            EventId = new Guid("09189be9-c6ff-4f4c-9c6c-db8517d9530b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6532),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("94cbe845-a891-485f-87b7-11e6801ef95f"),
                            EventId = new Guid("09189be9-c6ff-4f4c-9c6c-db8517d9530b"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6533),
                            VisitorEmail = "sarah.wilson@example.com",
                            VisitorFirstName = "Sarah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VisitorLastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("6e45f3e5-decc-4377-8d7c-c0b39f15a359"),
                            EventId = new Guid("0e5b218c-bca8-4989-8454-ed869ff1f951"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6535),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("1659021e-8f50-4ef5-8806-ac5ffd8a5e5f"),
                            EventId = new Guid("0e5b218c-bca8-4989-8454-ed869ff1f951"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6538),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("cdb0d883-8112-4001-93a3-63def7623e14"),
                            EventId = new Guid("0b5063d3-cf21-4c5a-9c40-4f7418ff5948"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6548),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("0e3360b8-95f6-4a21-b0c1-3c21f4e9be59"),
                            EventId = new Guid("0b5063d3-cf21-4c5a-9c40-4f7418ff5948"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6551),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("90344166-2fae-43aa-a3be-a152ae7e9096"),
                            EventId = new Guid("0b5063d3-cf21-4c5a-9c40-4f7418ff5948"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6552),
                            VisitorEmail = "hannah.collins@example.com",
                            VisitorFirstName = "Hannah",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000025"),
                            VisitorLastName = "Collins"
                        },
                        new
                        {
                            Id = new Guid("7250f6ed-5da0-4030-b555-9255fc1d52a9"),
                            EventId = new Guid("0b5063d3-cf21-4c5a-9c40-4f7418ff5948"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6553),
                            VisitorEmail = "isaac.stewart@example.com",
                            VisitorFirstName = "Isaac",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000026"),
                            VisitorLastName = "Stewart"
                        },
                        new
                        {
                            Id = new Guid("08f51c89-78d7-4c78-8c42-52b6128f0680"),
                            EventId = new Guid("0b5063d3-cf21-4c5a-9c40-4f7418ff5948"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6554),
                            VisitorEmail = "ethan.walker@example.com",
                            VisitorFirstName = "Ethan",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000012"),
                            VisitorLastName = "Walker"
                        },
                        new
                        {
                            Id = new Guid("d769c4a3-3e28-4bf2-8988-ed276562265b"),
                            EventId = new Guid("012740e4-3721-49ea-b91d-6b3bc0b8dc95"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6556),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("bb8c8f43-48cc-4d23-8ab5-f09651c0b18e"),
                            EventId = new Guid("012740e4-3721-49ea-b91d-6b3bc0b8dc95"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6557),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("efb8b1d9-b298-4638-9df5-4d4f6e48a641"),
                            EventId = new Guid("e5081037-258b-4944-854a-36542c9eb709"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6558),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("facc3602-8f42-49ae-b982-5faca5f3fd7d"),
                            EventId = new Guid("e5081037-258b-4944-854a-36542c9eb709"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6560),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("b0873bd6-96b2-4340-ab31-e2b6655ae2ae"),
                            EventId = new Guid("e5081037-258b-4944-854a-36542c9eb709"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6562),
                            VisitorEmail = "evelyn.hill@example.com",
                            VisitorFirstName = "Evelyn",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000016"),
                            VisitorLastName = "Hill"
                        },
                        new
                        {
                            Id = new Guid("cbd79b12-41dd-4166-971c-9008708b1434"),
                            EventId = new Guid("45d0162b-5f24-4881-a2c5-0426608656b5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6564),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("c77f54d9-9e98-42c5-86e8-3585fbd90cf7"),
                            EventId = new Guid("45d0162b-5f24-4881-a2c5-0426608656b5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6565),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("035a7ca3-656f-44c0-a8ca-99040ab84925"),
                            EventId = new Guid("e7c06fc3-4ba4-4179-a38c-2dc285710dd5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6566),
                            UserId = new Guid("ef6765de-e98d-4896-939d-58a46be39203")
                        },
                        new
                        {
                            Id = new Guid("15edc414-6c3b-4f3c-b4dd-53d47b8151d1"),
                            EventId = new Guid("e7c06fc3-4ba4-4179-a38c-2dc285710dd5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6567),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("566fca94-58e8-476f-a331-d2cf4c33a3d5"),
                            EventId = new Guid("e7c06fc3-4ba4-4179-a38c-2dc285710dd5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6568),
                            VisitorEmail = "david.martinez@example.com",
                            VisitorFirstName = "David",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            VisitorLastName = "Martinez"
                        },
                        new
                        {
                            Id = new Guid("bd32c1f5-99aa-46b7-ad11-97a42198e2ff"),
                            EventId = new Guid("e7c06fc3-4ba4-4179-a38c-2dc285710dd5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6570),
                            VisitorEmail = "caleb.reed@example.com",
                            VisitorFirstName = "Caleb",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000027"),
                            VisitorLastName = "Reed"
                        },
                        new
                        {
                            Id = new Guid("ffc0dc6c-94f8-460b-9f49-ea232741890b"),
                            EventId = new Guid("e7c06fc3-4ba4-4179-a38c-2dc285710dd5"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6571),
                            VisitorEmail = "scarlett.cook@example.com",
                            VisitorFirstName = "Scarlett",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000028"),
                            VisitorLastName = "Cook"
                        },
                        new
                        {
                            Id = new Guid("caba3952-6f7b-4743-bc05-9fa7092cfa8d"),
                            EventId = new Guid("9d1fcacd-47ce-4bbf-b692-785e84451c5e"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6574),
                            UserId = new Guid("524d798e-f599-4594-9824-e75ec3d22229")
                        },
                        new
                        {
                            Id = new Guid("15b66dce-1411-429e-9656-fcaaf8b81a55"),
                            EventId = new Guid("9d1fcacd-47ce-4bbf-b692-785e84451c5e"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6575),
                            UserId = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39")
                        },
                        new
                        {
                            Id = new Guid("943b8415-39ec-4ad1-ab86-fa551d2a323f"),
                            EventId = new Guid("9d1fcacd-47ce-4bbf-b692-785e84451c5e"),
                            JoinedAt = new DateTime(2025, 10, 20, 16, 37, 37, 377, DateTimeKind.Utc).AddTicks(6577),
                            VisitorEmail = "michael.brown@example.com",
                            VisitorFirstName = "Michael",
                            VisitorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VisitorLastName = "Brown"
                        });
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef6765de-e98d-4896-939d-58a46be39203"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("524d798e-f599-4594-9824-e75ec3d22229"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        },
                        new
                        {
                            Id = new Guid("95da1d65-6add-43aa-b507-cd653e2c6b39"),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$V2cYAlIQUgz1cAHT9elmteBzF.zj.Zc4pIIjRBHojluqcJKLMbbue"
                        });
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.HasOne("Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.EventParticipant", b =>
                {
                    b.HasOne("Domain.Models.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Event", b =>
                {
                    b.Navigation("EventParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
