services:
  angular-app:
    build:
      context: ./src/Web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - app-network
  
  api:
    image: api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    env_file:
      - .env
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - event-management.database
    networks:
      - app-network
  
  event-management.database:
    image: postgres:latest
    container_name: event-management.database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge